package com.wwl.storage.mappers;

import com.wwl.entity.AlipayMissData;

public interface AlipayMissDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_miss_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer aMDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_miss_data
     *
     * @mbggenerated
     */
    int insert(AlipayMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_miss_data
     *
     * @mbggenerated
     */
    int insertSelective(AlipayMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_miss_data
     *
     * @mbggenerated
     */
    AlipayMissData selectByPrimaryKey(Integer aMDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_miss_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlipayMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_miss_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlipayMissData record);
}