package com.wwl.storage.mappers;

import com.wwl.entity.GroupsAppend;

public interface GroupsAppendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ append
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gAppendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ append
     *
     * @mbggenerated
     */
    int insert(GroupsAppend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ append
     *
     * @mbggenerated
     */
    int insertSelective(GroupsAppend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ append
     *
     * @mbggenerated
     */
    GroupsAppend selectByPrimaryKey(Integer gAppendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ append
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsAppend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ append
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsAppend record);
}