package com.wwl.storage.mappers;

import com.wwl.entity.GroupsCar;

public interface GroupsCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gCarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_car
     *
     * @mbggenerated
     */
    int insert(GroupsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_car
     *
     * @mbggenerated
     */
    int insertSelective(GroupsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_car
     *
     * @mbggenerated
     */
    GroupsCar selectByPrimaryKey(Integer gCarId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsCar record);
}