package com.wwl.storage.mappers;

import com.wwl.entity.GroupsTrain;

public interface GroupsTrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_train
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gTrainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_train
     *
     * @mbggenerated
     */
    int insert(GroupsTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_train
     *
     * @mbggenerated
     */
    int insertSelective(GroupsTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_train
     *
     * @mbggenerated
     */
    GroupsTrain selectByPrimaryKey(Integer gTrainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_train
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_train
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsTrain record);
}