package com.wwl.storage.mappers;

import com.wwl.entity.GroupsTicket;

public interface GroupsTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ticket
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gTicketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ticket
     *
     * @mbggenerated
     */
    int insert(GroupsTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ticket
     *
     * @mbggenerated
     */
    int insertSelective(GroupsTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ticket
     *
     * @mbggenerated
     */
    GroupsTicket selectByPrimaryKey(Integer gTicketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsTicket record);
}