package com.wwl.storage.mappers;

import com.wwl.entity.GroupsVisa;

public interface GroupsVisaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_visa
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gVisaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_visa
     *
     * @mbggenerated
     */
    int insert(GroupsVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_visa
     *
     * @mbggenerated
     */
    int insertSelective(GroupsVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_visa
     *
     * @mbggenerated
     */
    GroupsVisa selectByPrimaryKey(Integer gVisaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_visa
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_visa
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsVisa record);
}