package com.wwl.storage.mappers;

import com.wwl.entity.GroupsAppendHotel;

public interface GroupsAppendHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_hotel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gAHotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_hotel
     *
     * @mbggenerated
     */
    int insert(GroupsAppendHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_hotel
     *
     * @mbggenerated
     */
    int insertSelective(GroupsAppendHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_hotel
     *
     * @mbggenerated
     */
    GroupsAppendHotel selectByPrimaryKey(Integer gAHotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsAppendHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsAppendHotel record);
}