package com.wwl.storage.mappers;

import com.wwl.entity.GroupsAppendOther;

public interface GroupsAppendOtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_other
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gAOtherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_other
     *
     * @mbggenerated
     */
    int insert(GroupsAppendOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_other
     *
     * @mbggenerated
     */
    int insertSelective(GroupsAppendOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_other
     *
     * @mbggenerated
     */
    GroupsAppendOther selectByPrimaryKey(Integer gAOtherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_other
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsAppendOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_other
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsAppendOther record);
}