package com.wwl.storage.mappers;

import com.wwl.entity.GroupsAppendVisa;

public interface GroupsAppendVisaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_visa
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gAVisaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_visa
     *
     * @mbggenerated
     */
    int insert(GroupsAppendVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_visa
     *
     * @mbggenerated
     */
    int insertSelective(GroupsAppendVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_visa
     *
     * @mbggenerated
     */
    GroupsAppendVisa selectByPrimaryKey(Integer gAVisaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_visa
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsAppendVisa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_visa
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsAppendVisa record);
}