package com.wwl.storage.mappers;

import com.wwl.entity.GroupsOther;

public interface GroupsOtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_other
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gOtherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_other
     *
     * @mbggenerated
     */
    int insert(GroupsOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_other
     *
     * @mbggenerated
     */
    int insertSelective(GroupsOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_other
     *
     * @mbggenerated
     */
    GroupsOther selectByPrimaryKey(Integer gOtherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_other
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_other
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsOther record);
}