package com.wwl.storage.mappers;

import com.wwl.entity.GroupsHotel;

public interface GroupsHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_hotel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gHotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_hotel
     *
     * @mbggenerated
     */
    int insert(GroupsHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_hotel
     *
     * @mbggenerated
     */
    int insertSelective(GroupsHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_hotel
     *
     * @mbggenerated
     */
    GroupsHotel selectByPrimaryKey(Integer gHotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_hotel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsHotel record);
}