package com.wwl.storage.mappers;

import com.wwl.entity.GroupsAppendTicket;

public interface GroupsAppendTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_ticket
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gATicketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_ticket
     *
     * @mbggenerated
     */
    int insert(GroupsAppendTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_ticket
     *
     * @mbggenerated
     */
    int insertSelective(GroupsAppendTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_ticket
     *
     * @mbggenerated
     */
    GroupsAppendTicket selectByPrimaryKey(Integer gATicketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupsAppendTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups_append_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupsAppendTicket record);
}