package com.wwl.storage.mappers;

import com.wwl.entity.PayType;

public interface PayTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_type
     *
     * @mbggenerated
     */
    int insert(PayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_type
     *
     * @mbggenerated
     */
    int insertSelective(PayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_type
     *
     * @mbggenerated
     */
    PayType selectByPrimaryKey(Integer pTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayType record);
}