package com.wwl.storage.mappers;

import com.wwl.entity.PlatformMissData;

public interface PlatformMissDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_miss_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pMDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_miss_data
     *
     * @mbggenerated
     */
    int insert(PlatformMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_miss_data
     *
     * @mbggenerated
     */
    int insertSelective(PlatformMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_miss_data
     *
     * @mbggenerated
     */
    PlatformMissData selectByPrimaryKey(Integer pMDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_miss_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlatformMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_miss_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlatformMissData record);
}