package com.wwl.storage.mappers;
import com.wwl.entity.Reconciliation;
import com.wwl.entity.ReconciliationExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface ReconciliationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int countByExample(ReconciliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int deleteByExample(ReconciliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int deleteByPrimaryKey(Integer reconciliationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int insert(Reconciliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int insertSelective(Reconciliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    List<Reconciliation> selectByExample(ReconciliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    Reconciliation selectByPrimaryKey(Integer reconciliationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") Reconciliation record, @Param("example") ReconciliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int updateByExample(@Param("record") Reconciliation record, @Param("example") ReconciliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int updateByPrimaryKeySelective(Reconciliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reconciliation
     *
     * @ Fri Nov 20 14:42:37 CST 2015
     */
    int updateByPrimaryKey(Reconciliation record);


    List<Reconciliation> findAllReconByCondition(Map mp);
}