package com.wwl.storage.mappers;

import com.wwl.entity.ReconciliationDetail;

public interface ReconciliationDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_detail
     *
     * @mbggenerated
     */
    int insert(ReconciliationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_detail
     *
     * @mbggenerated
     */
    int insertSelective(ReconciliationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_detail
     *
     * @mbggenerated
     */
    ReconciliationDetail selectByPrimaryKey(Integer rDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReconciliationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReconciliationDetail record);
}