package com.wwl.storage.mappers;

import com.wwl.entity.SettlementType;

public interface SettlementTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_type
     *
     * @mbggenerated
     */
    int insert(SettlementType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_type
     *
     * @mbggenerated
     */
    int insertSelective(SettlementType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_type
     *
     * @mbggenerated
     */
    SettlementType selectByPrimaryKey(Integer sTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SettlementType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SettlementType record);
}