package com.wwl.storage.mappers;

import com.wwl.entity.TenpayMissData;

public interface TenpayMissDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenpay_miss_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tMDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenpay_miss_data
     *
     * @mbggenerated
     */
    int insert(TenpayMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenpay_miss_data
     *
     * @mbggenerated
     */
    int insertSelective(TenpayMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenpay_miss_data
     *
     * @mbggenerated
     */
    TenpayMissData selectByPrimaryKey(Integer tMDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenpay_miss_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TenpayMissData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenpay_miss_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TenpayMissData record);
}