package com.wwl.storage.mappers;

import com.wwl.entity.UserMenu;

public interface UserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int insert(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int insertSelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    UserMenu selectByPrimaryKey(Integer uMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserMenu record);
}