package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AlipayMissData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_id
     *
     * @mbggenerated
     */
    private Integer aMDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_ddh
     *
     * @mbggenerated
     */
    private String aMDataDdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_yddh
     *
     * @mbggenerated
     */
    private String aMDataYddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_lx
     *
     * @mbggenerated
     */
    private String aMDataLx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_je
     *
     * @mbggenerated
     */
    private BigDecimal aMDataJe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_sxf
     *
     * @mbggenerated
     */
    private BigDecimal aMDataSxf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_ptbk
     *
     * @mbggenerated
     */
    private BigDecimal aMDataPtbk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.a_m_data_bz
     *
     * @mbggenerated
     */
    private String aMDataBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_miss_data.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_id
     *
     * @return the value of alipay_miss_data.a_m_data_id
     *
     * @mbggenerated
     */
    public Integer getaMDataId() {
        return aMDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_id
     *
     * @param aMDataId the value for alipay_miss_data.a_m_data_id
     *
     * @mbggenerated
     */
    public void setaMDataId(Integer aMDataId) {
        this.aMDataId = aMDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_ddh
     *
     * @return the value of alipay_miss_data.a_m_data_ddh
     *
     * @mbggenerated
     */
    public String getaMDataDdh() {
        return aMDataDdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_ddh
     *
     * @param aMDataDdh the value for alipay_miss_data.a_m_data_ddh
     *
     * @mbggenerated
     */
    public void setaMDataDdh(String aMDataDdh) {
        this.aMDataDdh = aMDataDdh == null ? null : aMDataDdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_yddh
     *
     * @return the value of alipay_miss_data.a_m_data_yddh
     *
     * @mbggenerated
     */
    public String getaMDataYddh() {
        return aMDataYddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_yddh
     *
     * @param aMDataYddh the value for alipay_miss_data.a_m_data_yddh
     *
     * @mbggenerated
     */
    public void setaMDataYddh(String aMDataYddh) {
        this.aMDataYddh = aMDataYddh == null ? null : aMDataYddh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_lx
     *
     * @return the value of alipay_miss_data.a_m_data_lx
     *
     * @mbggenerated
     */
    public String getaMDataLx() {
        return aMDataLx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_lx
     *
     * @param aMDataLx the value for alipay_miss_data.a_m_data_lx
     *
     * @mbggenerated
     */
    public void setaMDataLx(String aMDataLx) {
        this.aMDataLx = aMDataLx == null ? null : aMDataLx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_je
     *
     * @return the value of alipay_miss_data.a_m_data_je
     *
     * @mbggenerated
     */
    public BigDecimal getaMDataJe() {
        return aMDataJe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_je
     *
     * @param aMDataJe the value for alipay_miss_data.a_m_data_je
     *
     * @mbggenerated
     */
    public void setaMDataJe(BigDecimal aMDataJe) {
        this.aMDataJe = aMDataJe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_sxf
     *
     * @return the value of alipay_miss_data.a_m_data_sxf
     *
     * @mbggenerated
     */
    public BigDecimal getaMDataSxf() {
        return aMDataSxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_sxf
     *
     * @param aMDataSxf the value for alipay_miss_data.a_m_data_sxf
     *
     * @mbggenerated
     */
    public void setaMDataSxf(BigDecimal aMDataSxf) {
        this.aMDataSxf = aMDataSxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_ptbk
     *
     * @return the value of alipay_miss_data.a_m_data_ptbk
     *
     * @mbggenerated
     */
    public BigDecimal getaMDataPtbk() {
        return aMDataPtbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_ptbk
     *
     * @param aMDataPtbk the value for alipay_miss_data.a_m_data_ptbk
     *
     * @mbggenerated
     */
    public void setaMDataPtbk(BigDecimal aMDataPtbk) {
        this.aMDataPtbk = aMDataPtbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.a_m_data_bz
     *
     * @return the value of alipay_miss_data.a_m_data_bz
     *
     * @mbggenerated
     */
    public String getaMDataBz() {
        return aMDataBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.a_m_data_bz
     *
     * @param aMDataBz the value for alipay_miss_data.a_m_data_bz
     *
     * @mbggenerated
     */
    public void setaMDataBz(String aMDataBz) {
        this.aMDataBz = aMDataBz == null ? null : aMDataBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.createtime
     *
     * @return the value of alipay_miss_data.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.createtime
     *
     * @param createtime the value for alipay_miss_data.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_miss_data.createuser
     *
     * @return the value of alipay_miss_data.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_miss_data.createuser
     *
     * @param createuser the value for alipay_miss_data.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}