package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_js_type_id
     *
     * @mbggenerated
     */
    private Integer companyJsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_lxr
     *
     * @mbggenerated
     */
    private String companyLxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_lxdh
     *
     * @mbggenerated
     */
    private String companyLxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_bz
     *
     * @mbggenerated
     */
    private String companyBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_sfje
     *
     * @mbggenerated
     */
    private BigDecimal companySfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_ssje
     *
     * @mbggenerated
     */
    private BigDecimal companySsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_qnsfje
     *
     * @mbggenerated
     */
    private BigDecimal companyQnsfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_qnssje
     *
     * @mbggenerated
     */
    private BigDecimal companyQnssje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_lnsfje
     *
     * @mbggenerated
     */
    private BigDecimal companyLnsfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_lnssje
     *
     * @mbggenerated
     */
    private BigDecimal companyLnssje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_id
     *
     * @return the value of company.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_id
     *
     * @param companyId the value for company.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param companyName the value for company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_js_type_id
     *
     * @return the value of company.company_js_type_id
     *
     * @mbggenerated
     */
    public Integer getCompanyJsTypeId() {
        return companyJsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_js_type_id
     *
     * @param companyJsTypeId the value for company.company_js_type_id
     *
     * @mbggenerated
     */
    public void setCompanyJsTypeId(Integer companyJsTypeId) {
        this.companyJsTypeId = companyJsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_lxr
     *
     * @return the value of company.company_lxr
     *
     * @mbggenerated
     */
    public String getCompanyLxr() {
        return companyLxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_lxr
     *
     * @param companyLxr the value for company.company_lxr
     *
     * @mbggenerated
     */
    public void setCompanyLxr(String companyLxr) {
        this.companyLxr = companyLxr == null ? null : companyLxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_lxdh
     *
     * @return the value of company.company_lxdh
     *
     * @mbggenerated
     */
    public String getCompanyLxdh() {
        return companyLxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_lxdh
     *
     * @param companyLxdh the value for company.company_lxdh
     *
     * @mbggenerated
     */
    public void setCompanyLxdh(String companyLxdh) {
        this.companyLxdh = companyLxdh == null ? null : companyLxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_bz
     *
     * @return the value of company.company_bz
     *
     * @mbggenerated
     */
    public String getCompanyBz() {
        return companyBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_bz
     *
     * @param companyBz the value for company.company_bz
     *
     * @mbggenerated
     */
    public void setCompanyBz(String companyBz) {
        this.companyBz = companyBz == null ? null : companyBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_sfje
     *
     * @return the value of company.company_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getCompanySfje() {
        return companySfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_sfje
     *
     * @param companySfje the value for company.company_sfje
     *
     * @mbggenerated
     */
    public void setCompanySfje(BigDecimal companySfje) {
        this.companySfje = companySfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_ssje
     *
     * @return the value of company.company_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getCompanySsje() {
        return companySsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_ssje
     *
     * @param companySsje the value for company.company_ssje
     *
     * @mbggenerated
     */
    public void setCompanySsje(BigDecimal companySsje) {
        this.companySsje = companySsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_qnsfje
     *
     * @return the value of company.company_qnsfje
     *
     * @mbggenerated
     */
    public BigDecimal getCompanyQnsfje() {
        return companyQnsfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_qnsfje
     *
     * @param companyQnsfje the value for company.company_qnsfje
     *
     * @mbggenerated
     */
    public void setCompanyQnsfje(BigDecimal companyQnsfje) {
        this.companyQnsfje = companyQnsfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_qnssje
     *
     * @return the value of company.company_qnssje
     *
     * @mbggenerated
     */
    public BigDecimal getCompanyQnssje() {
        return companyQnssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_qnssje
     *
     * @param companyQnssje the value for company.company_qnssje
     *
     * @mbggenerated
     */
    public void setCompanyQnssje(BigDecimal companyQnssje) {
        this.companyQnssje = companyQnssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_lnsfje
     *
     * @return the value of company.company_lnsfje
     *
     * @mbggenerated
     */
    public BigDecimal getCompanyLnsfje() {
        return companyLnsfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_lnsfje
     *
     * @param companyLnsfje the value for company.company_lnsfje
     *
     * @mbggenerated
     */
    public void setCompanyLnsfje(BigDecimal companyLnsfje) {
        this.companyLnsfje = companyLnsfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_lnssje
     *
     * @return the value of company.company_lnssje
     *
     * @mbggenerated
     */
    public BigDecimal getCompanyLnssje() {
        return companyLnssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_lnssje
     *
     * @param companyLnssje the value for company.company_lnssje
     *
     * @mbggenerated
     */
    public void setCompanyLnssje(BigDecimal companyLnssje) {
        this.companyLnssje = companyLnssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.createtime
     *
     * @return the value of company.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.createtime
     *
     * @param createtime the value for company.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.createuser
     *
     * @return the value of company.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.createuser
     *
     * @param createuser the value for company.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}