package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsVisa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_id
     *
     * @mbggenerated
     */
    private Integer gVisaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_groups_id
     *
     * @mbggenerated
     */
    private Integer gVisaGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_createdate
     *
     * @mbggenerated
     */
    private Date gVisaCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_name
     *
     * @mbggenerated
     */
    private String gVisaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_type
     *
     * @mbggenerated
     */
    private String gVisaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_people
     *
     * @mbggenerated
     */
    private Integer gVisaPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gVisaPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gVisaSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_visa_dj
     *
     * @mbggenerated
     */
    private BigDecimal gVisaDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_train_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gTrainFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.g_train_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gTrainSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_visa.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_id
     *
     * @return the value of groups_visa.g_visa_id
     *
     * @mbggenerated
     */
    public Integer getgVisaId() {
        return gVisaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_id
     *
     * @param gVisaId the value for groups_visa.g_visa_id
     *
     * @mbggenerated
     */
    public void setgVisaId(Integer gVisaId) {
        this.gVisaId = gVisaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_groups_id
     *
     * @return the value of groups_visa.g_visa_groups_id
     *
     * @mbggenerated
     */
    public Integer getgVisaGroupsId() {
        return gVisaGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_groups_id
     *
     * @param gVisaGroupsId the value for groups_visa.g_visa_groups_id
     *
     * @mbggenerated
     */
    public void setgVisaGroupsId(Integer gVisaGroupsId) {
        this.gVisaGroupsId = gVisaGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_createdate
     *
     * @return the value of groups_visa.g_visa_createdate
     *
     * @mbggenerated
     */
    public Date getgVisaCreatedate() {
        return gVisaCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_createdate
     *
     * @param gVisaCreatedate the value for groups_visa.g_visa_createdate
     *
     * @mbggenerated
     */
    public void setgVisaCreatedate(Date gVisaCreatedate) {
        this.gVisaCreatedate = gVisaCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_name
     *
     * @return the value of groups_visa.g_visa_name
     *
     * @mbggenerated
     */
    public String getgVisaName() {
        return gVisaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_name
     *
     * @param gVisaName the value for groups_visa.g_visa_name
     *
     * @mbggenerated
     */
    public void setgVisaName(String gVisaName) {
        this.gVisaName = gVisaName == null ? null : gVisaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_type
     *
     * @return the value of groups_visa.g_visa_type
     *
     * @mbggenerated
     */
    public String getgVisaType() {
        return gVisaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_type
     *
     * @param gVisaType the value for groups_visa.g_visa_type
     *
     * @mbggenerated
     */
    public void setgVisaType(String gVisaType) {
        this.gVisaType = gVisaType == null ? null : gVisaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_people
     *
     * @return the value of groups_visa.g_visa_people
     *
     * @mbggenerated
     */
    public Integer getgVisaPeople() {
        return gVisaPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_people
     *
     * @param gVisaPeople the value for groups_visa.g_visa_people
     *
     * @mbggenerated
     */
    public void setgVisaPeople(Integer gVisaPeople) {
        this.gVisaPeople = gVisaPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_pay_type_id
     *
     * @return the value of groups_visa.g_visa_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgVisaPayTypeId() {
        return gVisaPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_pay_type_id
     *
     * @param gVisaPayTypeId the value for groups_visa.g_visa_pay_type_id
     *
     * @mbggenerated
     */
    public void setgVisaPayTypeId(Integer gVisaPayTypeId) {
        this.gVisaPayTypeId = gVisaPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_sfje
     *
     * @return the value of groups_visa.g_visa_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgVisaSfje() {
        return gVisaSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_sfje
     *
     * @param gVisaSfje the value for groups_visa.g_visa_sfje
     *
     * @mbggenerated
     */
    public void setgVisaSfje(BigDecimal gVisaSfje) {
        this.gVisaSfje = gVisaSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_visa_dj
     *
     * @return the value of groups_visa.g_visa_dj
     *
     * @mbggenerated
     */
    public BigDecimal getgVisaDj() {
        return gVisaDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_visa_dj
     *
     * @param gVisaDj the value for groups_visa.g_visa_dj
     *
     * @mbggenerated
     */
    public void setgVisaDj(BigDecimal gVisaDj) {
        this.gVisaDj = gVisaDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_train_fwf
     *
     * @return the value of groups_visa.g_train_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgTrainFwf() {
        return gTrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_train_fwf
     *
     * @param gTrainFwf the value for groups_visa.g_train_fwf
     *
     * @mbggenerated
     */
    public void setgTrainFwf(BigDecimal gTrainFwf) {
        this.gTrainFwf = gTrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.g_train_ssje
     *
     * @return the value of groups_visa.g_train_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgTrainSsje() {
        return gTrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.g_train_ssje
     *
     * @param gTrainSsje the value for groups_visa.g_train_ssje
     *
     * @mbggenerated
     */
    public void setgTrainSsje(BigDecimal gTrainSsje) {
        this.gTrainSsje = gTrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.createtime
     *
     * @return the value of groups_visa.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.createtime
     *
     * @param createtime the value for groups_visa.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_visa.createuser
     *
     * @return the value of groups_visa.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_visa.createuser
     *
     * @param createuser the value for groups_visa.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}