package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_id
     *
     * @mbggenerated
     */
    private Integer gCarId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_groups_id
     *
     * @mbggenerated
     */
    private Integer gCarGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_createdate
     *
     * @mbggenerated
     */
    private Date gCarCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_name
     *
     * @mbggenerated
     */
    private String gCarName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_type
     *
     * @mbggenerated
     */
    private String gCarType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_people
     *
     * @mbggenerated
     */
    private Integer gCarPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_count
     *
     * @mbggenerated
     */
    private Integer gCarCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gCarPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gCarSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gCarFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.g_car_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gCarSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_car.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_id
     *
     * @return the value of groups_car.g_car_id
     *
     * @mbggenerated
     */
    public Integer getgCarId() {
        return gCarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_id
     *
     * @param gCarId the value for groups_car.g_car_id
     *
     * @mbggenerated
     */
    public void setgCarId(Integer gCarId) {
        this.gCarId = gCarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_groups_id
     *
     * @return the value of groups_car.g_car_groups_id
     *
     * @mbggenerated
     */
    public Integer getgCarGroupsId() {
        return gCarGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_groups_id
     *
     * @param gCarGroupsId the value for groups_car.g_car_groups_id
     *
     * @mbggenerated
     */
    public void setgCarGroupsId(Integer gCarGroupsId) {
        this.gCarGroupsId = gCarGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_createdate
     *
     * @return the value of groups_car.g_car_createdate
     *
     * @mbggenerated
     */
    public Date getgCarCreatedate() {
        return gCarCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_createdate
     *
     * @param gCarCreatedate the value for groups_car.g_car_createdate
     *
     * @mbggenerated
     */
    public void setgCarCreatedate(Date gCarCreatedate) {
        this.gCarCreatedate = gCarCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_name
     *
     * @return the value of groups_car.g_car_name
     *
     * @mbggenerated
     */
    public String getgCarName() {
        return gCarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_name
     *
     * @param gCarName the value for groups_car.g_car_name
     *
     * @mbggenerated
     */
    public void setgCarName(String gCarName) {
        this.gCarName = gCarName == null ? null : gCarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_type
     *
     * @return the value of groups_car.g_car_type
     *
     * @mbggenerated
     */
    public String getgCarType() {
        return gCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_type
     *
     * @param gCarType the value for groups_car.g_car_type
     *
     * @mbggenerated
     */
    public void setgCarType(String gCarType) {
        this.gCarType = gCarType == null ? null : gCarType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_people
     *
     * @return the value of groups_car.g_car_people
     *
     * @mbggenerated
     */
    public Integer getgCarPeople() {
        return gCarPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_people
     *
     * @param gCarPeople the value for groups_car.g_car_people
     *
     * @mbggenerated
     */
    public void setgCarPeople(Integer gCarPeople) {
        this.gCarPeople = gCarPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_count
     *
     * @return the value of groups_car.g_car_count
     *
     * @mbggenerated
     */
    public Integer getgCarCount() {
        return gCarCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_count
     *
     * @param gCarCount the value for groups_car.g_car_count
     *
     * @mbggenerated
     */
    public void setgCarCount(Integer gCarCount) {
        this.gCarCount = gCarCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_pay_type_id
     *
     * @return the value of groups_car.g_car_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgCarPayTypeId() {
        return gCarPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_pay_type_id
     *
     * @param gCarPayTypeId the value for groups_car.g_car_pay_type_id
     *
     * @mbggenerated
     */
    public void setgCarPayTypeId(Integer gCarPayTypeId) {
        this.gCarPayTypeId = gCarPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_sfje
     *
     * @return the value of groups_car.g_car_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgCarSfje() {
        return gCarSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_sfje
     *
     * @param gCarSfje the value for groups_car.g_car_sfje
     *
     * @mbggenerated
     */
    public void setgCarSfje(BigDecimal gCarSfje) {
        this.gCarSfje = gCarSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_fwf
     *
     * @return the value of groups_car.g_car_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgCarFwf() {
        return gCarFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_fwf
     *
     * @param gCarFwf the value for groups_car.g_car_fwf
     *
     * @mbggenerated
     */
    public void setgCarFwf(BigDecimal gCarFwf) {
        this.gCarFwf = gCarFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.g_car_ssje
     *
     * @return the value of groups_car.g_car_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgCarSsje() {
        return gCarSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.g_car_ssje
     *
     * @param gCarSsje the value for groups_car.g_car_ssje
     *
     * @mbggenerated
     */
    public void setgCarSsje(BigDecimal gCarSsje) {
        this.gCarSsje = gCarSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.createtime
     *
     * @return the value of groups_car.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.createtime
     *
     * @param createtime the value for groups_car.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_car.createuser
     *
     * @return the value of groups_car.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_car.createuser
     *
     * @param createuser the value for groups_car.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}