package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_id
     *
     * @mbggenerated
     */
    private Integer gAppendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_groups_id
     *
     * @mbggenerated
     */
    private Integer gAppendGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_groups_name
     *
     * @mbggenerated
     */
    private String gAppendGroupsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_count
     *
     * @mbggenerated
     */
    private Integer gAppendCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gAppendSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_fl
     *
     * @mbggenerated
     */
    private BigDecimal gAppendFl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gAppendFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gAppendSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.g_append_status
     *
     * @mbggenerated
     */
    private Integer gAppendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ append.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_id
     *
     * @return the value of groups_ append.g_append_id
     *
     * @mbggenerated
     */
    public Integer getgAppendId() {
        return gAppendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_id
     *
     * @param gAppendId the value for groups_ append.g_append_id
     *
     * @mbggenerated
     */
    public void setgAppendId(Integer gAppendId) {
        this.gAppendId = gAppendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_groups_id
     *
     * @return the value of groups_ append.g_append_groups_id
     *
     * @mbggenerated
     */
    public Integer getgAppendGroupsId() {
        return gAppendGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_groups_id
     *
     * @param gAppendGroupsId the value for groups_ append.g_append_groups_id
     *
     * @mbggenerated
     */
    public void setgAppendGroupsId(Integer gAppendGroupsId) {
        this.gAppendGroupsId = gAppendGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_groups_name
     *
     * @return the value of groups_ append.g_append_groups_name
     *
     * @mbggenerated
     */
    public String getgAppendGroupsName() {
        return gAppendGroupsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_groups_name
     *
     * @param gAppendGroupsName the value for groups_ append.g_append_groups_name
     *
     * @mbggenerated
     */
    public void setgAppendGroupsName(String gAppendGroupsName) {
        this.gAppendGroupsName = gAppendGroupsName == null ? null : gAppendGroupsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_count
     *
     * @return the value of groups_ append.g_append_count
     *
     * @mbggenerated
     */
    public Integer getgAppendCount() {
        return gAppendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_count
     *
     * @param gAppendCount the value for groups_ append.g_append_count
     *
     * @mbggenerated
     */
    public void setgAppendCount(Integer gAppendCount) {
        this.gAppendCount = gAppendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_sfje
     *
     * @return the value of groups_ append.g_append_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgAppendSfje() {
        return gAppendSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_sfje
     *
     * @param gAppendSfje the value for groups_ append.g_append_sfje
     *
     * @mbggenerated
     */
    public void setgAppendSfje(BigDecimal gAppendSfje) {
        this.gAppendSfje = gAppendSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_fl
     *
     * @return the value of groups_ append.g_append_fl
     *
     * @mbggenerated
     */
    public BigDecimal getgAppendFl() {
        return gAppendFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_fl
     *
     * @param gAppendFl the value for groups_ append.g_append_fl
     *
     * @mbggenerated
     */
    public void setgAppendFl(BigDecimal gAppendFl) {
        this.gAppendFl = gAppendFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_fwf
     *
     * @return the value of groups_ append.g_append_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgAppendFwf() {
        return gAppendFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_fwf
     *
     * @param gAppendFwf the value for groups_ append.g_append_fwf
     *
     * @mbggenerated
     */
    public void setgAppendFwf(BigDecimal gAppendFwf) {
        this.gAppendFwf = gAppendFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_ssje
     *
     * @return the value of groups_ append.g_append_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgAppendSsje() {
        return gAppendSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_ssje
     *
     * @param gAppendSsje the value for groups_ append.g_append_ssje
     *
     * @mbggenerated
     */
    public void setgAppendSsje(BigDecimal gAppendSsje) {
        this.gAppendSsje = gAppendSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.g_append_status
     *
     * @return the value of groups_ append.g_append_status
     *
     * @mbggenerated
     */
    public Integer getgAppendStatus() {
        return gAppendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.g_append_status
     *
     * @param gAppendStatus the value for groups_ append.g_append_status
     *
     * @mbggenerated
     */
    public void setgAppendStatus(Integer gAppendStatus) {
        this.gAppendStatus = gAppendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.createtime
     *
     * @return the value of groups_ append.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.createtime
     *
     * @param createtime the value for groups_ append.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ append.createuser
     *
     * @return the value of groups_ append.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ append.createuser
     *
     * @param createuser the value for groups_ append.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}