package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsTrain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_id
     *
     * @mbggenerated
     */
    private Integer gTrainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_groups_id
     *
     * @mbggenerated
     */
    private Integer gTrainGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_createdate
     *
     * @mbggenerated
     */
    private Date gTrainCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_name
     *
     * @mbggenerated
     */
    private String gTrainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_orderno
     *
     * @mbggenerated
     */
    private String gTrainOrderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_xb
     *
     * @mbggenerated
     */
    private String gTrainXb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_from
     *
     * @mbggenerated
     */
    private String gTrainFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_to
     *
     * @mbggenerated
     */
    private String gTrainTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_start_date
     *
     * @mbggenerated
     */
    private Date gTrainStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_number
     *
     * @mbggenerated
     */
    private String gTrainNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gTrainPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gTrainSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gTrainFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gTrainSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_skrq
     *
     * @mbggenerated
     */
    private Date gTrainSkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.g_train_tkrq
     *
     * @mbggenerated
     */
    private Date gTrainTkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_train.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_id
     *
     * @return the value of groups_train.g_train_id
     *
     * @mbggenerated
     */
    public Integer getgTrainId() {
        return gTrainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_id
     *
     * @param gTrainId the value for groups_train.g_train_id
     *
     * @mbggenerated
     */
    public void setgTrainId(Integer gTrainId) {
        this.gTrainId = gTrainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_groups_id
     *
     * @return the value of groups_train.g_train_groups_id
     *
     * @mbggenerated
     */
    public Integer getgTrainGroupsId() {
        return gTrainGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_groups_id
     *
     * @param gTrainGroupsId the value for groups_train.g_train_groups_id
     *
     * @mbggenerated
     */
    public void setgTrainGroupsId(Integer gTrainGroupsId) {
        this.gTrainGroupsId = gTrainGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_createdate
     *
     * @return the value of groups_train.g_train_createdate
     *
     * @mbggenerated
     */
    public Date getgTrainCreatedate() {
        return gTrainCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_createdate
     *
     * @param gTrainCreatedate the value for groups_train.g_train_createdate
     *
     * @mbggenerated
     */
    public void setgTrainCreatedate(Date gTrainCreatedate) {
        this.gTrainCreatedate = gTrainCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_name
     *
     * @return the value of groups_train.g_train_name
     *
     * @mbggenerated
     */
    public String getgTrainName() {
        return gTrainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_name
     *
     * @param gTrainName the value for groups_train.g_train_name
     *
     * @mbggenerated
     */
    public void setgTrainName(String gTrainName) {
        this.gTrainName = gTrainName == null ? null : gTrainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_orderno
     *
     * @return the value of groups_train.g_train_orderno
     *
     * @mbggenerated
     */
    public String getgTrainOrderno() {
        return gTrainOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_orderno
     *
     * @param gTrainOrderno the value for groups_train.g_train_orderno
     *
     * @mbggenerated
     */
    public void setgTrainOrderno(String gTrainOrderno) {
        this.gTrainOrderno = gTrainOrderno == null ? null : gTrainOrderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_xb
     *
     * @return the value of groups_train.g_train_xb
     *
     * @mbggenerated
     */
    public String getgTrainXb() {
        return gTrainXb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_xb
     *
     * @param gTrainXb the value for groups_train.g_train_xb
     *
     * @mbggenerated
     */
    public void setgTrainXb(String gTrainXb) {
        this.gTrainXb = gTrainXb == null ? null : gTrainXb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_from
     *
     * @return the value of groups_train.g_train_from
     *
     * @mbggenerated
     */
    public String getgTrainFrom() {
        return gTrainFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_from
     *
     * @param gTrainFrom the value for groups_train.g_train_from
     *
     * @mbggenerated
     */
    public void setgTrainFrom(String gTrainFrom) {
        this.gTrainFrom = gTrainFrom == null ? null : gTrainFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_to
     *
     * @return the value of groups_train.g_train_to
     *
     * @mbggenerated
     */
    public String getgTrainTo() {
        return gTrainTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_to
     *
     * @param gTrainTo the value for groups_train.g_train_to
     *
     * @mbggenerated
     */
    public void setgTrainTo(String gTrainTo) {
        this.gTrainTo = gTrainTo == null ? null : gTrainTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_start_date
     *
     * @return the value of groups_train.g_train_start_date
     *
     * @mbggenerated
     */
    public Date getgTrainStartDate() {
        return gTrainStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_start_date
     *
     * @param gTrainStartDate the value for groups_train.g_train_start_date
     *
     * @mbggenerated
     */
    public void setgTrainStartDate(Date gTrainStartDate) {
        this.gTrainStartDate = gTrainStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_number
     *
     * @return the value of groups_train.g_train_number
     *
     * @mbggenerated
     */
    public String getgTrainNumber() {
        return gTrainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_number
     *
     * @param gTrainNumber the value for groups_train.g_train_number
     *
     * @mbggenerated
     */
    public void setgTrainNumber(String gTrainNumber) {
        this.gTrainNumber = gTrainNumber == null ? null : gTrainNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_pay_type_id
     *
     * @return the value of groups_train.g_train_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgTrainPayTypeId() {
        return gTrainPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_pay_type_id
     *
     * @param gTrainPayTypeId the value for groups_train.g_train_pay_type_id
     *
     * @mbggenerated
     */
    public void setgTrainPayTypeId(Integer gTrainPayTypeId) {
        this.gTrainPayTypeId = gTrainPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_sfje
     *
     * @return the value of groups_train.g_train_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgTrainSfje() {
        return gTrainSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_sfje
     *
     * @param gTrainSfje the value for groups_train.g_train_sfje
     *
     * @mbggenerated
     */
    public void setgTrainSfje(BigDecimal gTrainSfje) {
        this.gTrainSfje = gTrainSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_fwf
     *
     * @return the value of groups_train.g_train_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgTrainFwf() {
        return gTrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_fwf
     *
     * @param gTrainFwf the value for groups_train.g_train_fwf
     *
     * @mbggenerated
     */
    public void setgTrainFwf(BigDecimal gTrainFwf) {
        this.gTrainFwf = gTrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_ssje
     *
     * @return the value of groups_train.g_train_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgTrainSsje() {
        return gTrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_ssje
     *
     * @param gTrainSsje the value for groups_train.g_train_ssje
     *
     * @mbggenerated
     */
    public void setgTrainSsje(BigDecimal gTrainSsje) {
        this.gTrainSsje = gTrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_skrq
     *
     * @return the value of groups_train.g_train_skrq
     *
     * @mbggenerated
     */
    public Date getgTrainSkrq() {
        return gTrainSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_skrq
     *
     * @param gTrainSkrq the value for groups_train.g_train_skrq
     *
     * @mbggenerated
     */
    public void setgTrainSkrq(Date gTrainSkrq) {
        this.gTrainSkrq = gTrainSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.g_train_tkrq
     *
     * @return the value of groups_train.g_train_tkrq
     *
     * @mbggenerated
     */
    public Date getgTrainTkrq() {
        return gTrainTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.g_train_tkrq
     *
     * @param gTrainTkrq the value for groups_train.g_train_tkrq
     *
     * @mbggenerated
     */
    public void setgTrainTkrq(Date gTrainTkrq) {
        this.gTrainTkrq = gTrainTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.createtime
     *
     * @return the value of groups_train.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.createtime
     *
     * @param createtime the value for groups_train.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_train.createuser
     *
     * @return the value of groups_train.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_train.createuser
     *
     * @param createuser the value for groups_train.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}