package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_id
     *
     * @mbggenerated
     */
    private Integer gTicketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_groups_id
     *
     * @mbggenerated
     */
    private Integer gTicketGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_createdate
     *
     * @mbggenerated
     */
    private Date gTicketCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_booker
     *
     * @mbggenerated
     */
    private String gTicketBooker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_passenger
     *
     * @mbggenerated
     */
    private String gTicketPassenger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_orderno
     *
     * @mbggenerated
     */
    private String gTicketOrderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_pnr
     *
     * @mbggenerated
     */
    private String gTicketPnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_cw
     *
     * @mbggenerated
     */
    private String gTicketCw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_ph
     *
     * @mbggenerated
     */
    private String gTicketPh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_from
     *
     * @mbggenerated
     */
    private String gTicketFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_to
     *
     * @mbggenerated
     */
    private String gTicketTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_date
     *
     * @mbggenerated
     */
    private Date gTicketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_no
     *
     * @mbggenerated
     */
    private String gTicketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gTicketPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gTicketSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_pmje
     *
     * @mbggenerated
     */
    private BigDecimal gTicketPmje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_sf
     *
     * @mbggenerated
     */
    private BigDecimal gTicketSf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gTicketSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_fl
     *
     * @mbggenerated
     */
    private BigDecimal gTicketFl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_lr
     *
     * @mbggenerated
     */
    private BigDecimal gTicketLr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_skrq
     *
     * @mbggenerated
     */
    private Date gTicketSkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_tkrq
     *
     * @mbggenerated
     */
    private Date gTicketTkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_bz
     *
     * @mbggenerated
     */
    private String gTicketBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.g_ticket_ssr
     *
     * @mbggenerated
     */
    private String gTicketSsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_ticket.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_id
     *
     * @return the value of groups_ticket.g_ticket_id
     *
     * @mbggenerated
     */
    public Integer getgTicketId() {
        return gTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_id
     *
     * @param gTicketId the value for groups_ticket.g_ticket_id
     *
     * @mbggenerated
     */
    public void setgTicketId(Integer gTicketId) {
        this.gTicketId = gTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_groups_id
     *
     * @return the value of groups_ticket.g_ticket_groups_id
     *
     * @mbggenerated
     */
    public Integer getgTicketGroupsId() {
        return gTicketGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_groups_id
     *
     * @param gTicketGroupsId the value for groups_ticket.g_ticket_groups_id
     *
     * @mbggenerated
     */
    public void setgTicketGroupsId(Integer gTicketGroupsId) {
        this.gTicketGroupsId = gTicketGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_createdate
     *
     * @return the value of groups_ticket.g_ticket_createdate
     *
     * @mbggenerated
     */
    public Date getgTicketCreatedate() {
        return gTicketCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_createdate
     *
     * @param gTicketCreatedate the value for groups_ticket.g_ticket_createdate
     *
     * @mbggenerated
     */
    public void setgTicketCreatedate(Date gTicketCreatedate) {
        this.gTicketCreatedate = gTicketCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_booker
     *
     * @return the value of groups_ticket.g_ticket_booker
     *
     * @mbggenerated
     */
    public String getgTicketBooker() {
        return gTicketBooker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_booker
     *
     * @param gTicketBooker the value for groups_ticket.g_ticket_booker
     *
     * @mbggenerated
     */
    public void setgTicketBooker(String gTicketBooker) {
        this.gTicketBooker = gTicketBooker == null ? null : gTicketBooker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_passenger
     *
     * @return the value of groups_ticket.g_ticket_passenger
     *
     * @mbggenerated
     */
    public String getgTicketPassenger() {
        return gTicketPassenger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_passenger
     *
     * @param gTicketPassenger the value for groups_ticket.g_ticket_passenger
     *
     * @mbggenerated
     */
    public void setgTicketPassenger(String gTicketPassenger) {
        this.gTicketPassenger = gTicketPassenger == null ? null : gTicketPassenger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_orderno
     *
     * @return the value of groups_ticket.g_ticket_orderno
     *
     * @mbggenerated
     */
    public String getgTicketOrderno() {
        return gTicketOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_orderno
     *
     * @param gTicketOrderno the value for groups_ticket.g_ticket_orderno
     *
     * @mbggenerated
     */
    public void setgTicketOrderno(String gTicketOrderno) {
        this.gTicketOrderno = gTicketOrderno == null ? null : gTicketOrderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_pnr
     *
     * @return the value of groups_ticket.g_ticket_pnr
     *
     * @mbggenerated
     */
    public String getgTicketPnr() {
        return gTicketPnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_pnr
     *
     * @param gTicketPnr the value for groups_ticket.g_ticket_pnr
     *
     * @mbggenerated
     */
    public void setgTicketPnr(String gTicketPnr) {
        this.gTicketPnr = gTicketPnr == null ? null : gTicketPnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_cw
     *
     * @return the value of groups_ticket.g_ticket_cw
     *
     * @mbggenerated
     */
    public String getgTicketCw() {
        return gTicketCw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_cw
     *
     * @param gTicketCw the value for groups_ticket.g_ticket_cw
     *
     * @mbggenerated
     */
    public void setgTicketCw(String gTicketCw) {
        this.gTicketCw = gTicketCw == null ? null : gTicketCw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_ph
     *
     * @return the value of groups_ticket.g_ticket_ph
     *
     * @mbggenerated
     */
    public String getgTicketPh() {
        return gTicketPh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_ph
     *
     * @param gTicketPh the value for groups_ticket.g_ticket_ph
     *
     * @mbggenerated
     */
    public void setgTicketPh(String gTicketPh) {
        this.gTicketPh = gTicketPh == null ? null : gTicketPh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_from
     *
     * @return the value of groups_ticket.g_ticket_from
     *
     * @mbggenerated
     */
    public String getgTicketFrom() {
        return gTicketFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_from
     *
     * @param gTicketFrom the value for groups_ticket.g_ticket_from
     *
     * @mbggenerated
     */
    public void setgTicketFrom(String gTicketFrom) {
        this.gTicketFrom = gTicketFrom == null ? null : gTicketFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_to
     *
     * @return the value of groups_ticket.g_ticket_to
     *
     * @mbggenerated
     */
    public String getgTicketTo() {
        return gTicketTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_to
     *
     * @param gTicketTo the value for groups_ticket.g_ticket_to
     *
     * @mbggenerated
     */
    public void setgTicketTo(String gTicketTo) {
        this.gTicketTo = gTicketTo == null ? null : gTicketTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_date
     *
     * @return the value of groups_ticket.g_ticket_date
     *
     * @mbggenerated
     */
    public Date getgTicketDate() {
        return gTicketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_date
     *
     * @param gTicketDate the value for groups_ticket.g_ticket_date
     *
     * @mbggenerated
     */
    public void setgTicketDate(Date gTicketDate) {
        this.gTicketDate = gTicketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_no
     *
     * @return the value of groups_ticket.g_ticket_no
     *
     * @mbggenerated
     */
    public String getgTicketNo() {
        return gTicketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_no
     *
     * @param gTicketNo the value for groups_ticket.g_ticket_no
     *
     * @mbggenerated
     */
    public void setgTicketNo(String gTicketNo) {
        this.gTicketNo = gTicketNo == null ? null : gTicketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_pay_type_id
     *
     * @return the value of groups_ticket.g_ticket_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgTicketPayTypeId() {
        return gTicketPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_pay_type_id
     *
     * @param gTicketPayTypeId the value for groups_ticket.g_ticket_pay_type_id
     *
     * @mbggenerated
     */
    public void setgTicketPayTypeId(Integer gTicketPayTypeId) {
        this.gTicketPayTypeId = gTicketPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_sfje
     *
     * @return the value of groups_ticket.g_ticket_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgTicketSfje() {
        return gTicketSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_sfje
     *
     * @param gTicketSfje the value for groups_ticket.g_ticket_sfje
     *
     * @mbggenerated
     */
    public void setgTicketSfje(BigDecimal gTicketSfje) {
        this.gTicketSfje = gTicketSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_pmje
     *
     * @return the value of groups_ticket.g_ticket_pmje
     *
     * @mbggenerated
     */
    public BigDecimal getgTicketPmje() {
        return gTicketPmje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_pmje
     *
     * @param gTicketPmje the value for groups_ticket.g_ticket_pmje
     *
     * @mbggenerated
     */
    public void setgTicketPmje(BigDecimal gTicketPmje) {
        this.gTicketPmje = gTicketPmje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_sf
     *
     * @return the value of groups_ticket.g_ticket_sf
     *
     * @mbggenerated
     */
    public BigDecimal getgTicketSf() {
        return gTicketSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_sf
     *
     * @param gTicketSf the value for groups_ticket.g_ticket_sf
     *
     * @mbggenerated
     */
    public void setgTicketSf(BigDecimal gTicketSf) {
        this.gTicketSf = gTicketSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_ssje
     *
     * @return the value of groups_ticket.g_ticket_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgTicketSsje() {
        return gTicketSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_ssje
     *
     * @param gTicketSsje the value for groups_ticket.g_ticket_ssje
     *
     * @mbggenerated
     */
    public void setgTicketSsje(BigDecimal gTicketSsje) {
        this.gTicketSsje = gTicketSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_fl
     *
     * @return the value of groups_ticket.g_ticket_fl
     *
     * @mbggenerated
     */
    public BigDecimal getgTicketFl() {
        return gTicketFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_fl
     *
     * @param gTicketFl the value for groups_ticket.g_ticket_fl
     *
     * @mbggenerated
     */
    public void setgTicketFl(BigDecimal gTicketFl) {
        this.gTicketFl = gTicketFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_lr
     *
     * @return the value of groups_ticket.g_ticket_lr
     *
     * @mbggenerated
     */
    public BigDecimal getgTicketLr() {
        return gTicketLr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_lr
     *
     * @param gTicketLr the value for groups_ticket.g_ticket_lr
     *
     * @mbggenerated
     */
    public void setgTicketLr(BigDecimal gTicketLr) {
        this.gTicketLr = gTicketLr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_skrq
     *
     * @return the value of groups_ticket.g_ticket_skrq
     *
     * @mbggenerated
     */
    public Date getgTicketSkrq() {
        return gTicketSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_skrq
     *
     * @param gTicketSkrq the value for groups_ticket.g_ticket_skrq
     *
     * @mbggenerated
     */
    public void setgTicketSkrq(Date gTicketSkrq) {
        this.gTicketSkrq = gTicketSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_tkrq
     *
     * @return the value of groups_ticket.g_ticket_tkrq
     *
     * @mbggenerated
     */
    public Date getgTicketTkrq() {
        return gTicketTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_tkrq
     *
     * @param gTicketTkrq the value for groups_ticket.g_ticket_tkrq
     *
     * @mbggenerated
     */
    public void setgTicketTkrq(Date gTicketTkrq) {
        this.gTicketTkrq = gTicketTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_bz
     *
     * @return the value of groups_ticket.g_ticket_bz
     *
     * @mbggenerated
     */
    public String getgTicketBz() {
        return gTicketBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_bz
     *
     * @param gTicketBz the value for groups_ticket.g_ticket_bz
     *
     * @mbggenerated
     */
    public void setgTicketBz(String gTicketBz) {
        this.gTicketBz = gTicketBz == null ? null : gTicketBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.g_ticket_ssr
     *
     * @return the value of groups_ticket.g_ticket_ssr
     *
     * @mbggenerated
     */
    public String getgTicketSsr() {
        return gTicketSsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.g_ticket_ssr
     *
     * @param gTicketSsr the value for groups_ticket.g_ticket_ssr
     *
     * @mbggenerated
     */
    public void setgTicketSsr(String gTicketSsr) {
        this.gTicketSsr = gTicketSsr == null ? null : gTicketSsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.createtime
     *
     * @return the value of groups_ticket.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.createtime
     *
     * @param createtime the value for groups_ticket.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_ticket.createuser
     *
     * @return the value of groups_ticket.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_ticket.createuser
     *
     * @param createuser the value for groups_ticket.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}