package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsOther {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_id
     *
     * @mbggenerated
     */
    private Integer gOtherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_groups_id
     *
     * @mbggenerated
     */
    private Integer gOtherGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_createdate
     *
     * @mbggenerated
     */
    private Date gOtherCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_name
     *
     * @mbggenerated
     */
    private String gOtherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_people
     *
     * @mbggenerated
     */
    private Integer gOtherPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_matter
     *
     * @mbggenerated
     */
    private String gOtherMatter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gOtherPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gOtherSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gOtherFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gOtherSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.g_other_bz
     *
     * @mbggenerated
     */
    private String gOtherBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_other.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_id
     *
     * @return the value of groups_other.g_other_id
     *
     * @mbggenerated
     */
    public Integer getgOtherId() {
        return gOtherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_id
     *
     * @param gOtherId the value for groups_other.g_other_id
     *
     * @mbggenerated
     */
    public void setgOtherId(Integer gOtherId) {
        this.gOtherId = gOtherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_groups_id
     *
     * @return the value of groups_other.g_other_groups_id
     *
     * @mbggenerated
     */
    public Integer getgOtherGroupsId() {
        return gOtherGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_groups_id
     *
     * @param gOtherGroupsId the value for groups_other.g_other_groups_id
     *
     * @mbggenerated
     */
    public void setgOtherGroupsId(Integer gOtherGroupsId) {
        this.gOtherGroupsId = gOtherGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_createdate
     *
     * @return the value of groups_other.g_other_createdate
     *
     * @mbggenerated
     */
    public Date getgOtherCreatedate() {
        return gOtherCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_createdate
     *
     * @param gOtherCreatedate the value for groups_other.g_other_createdate
     *
     * @mbggenerated
     */
    public void setgOtherCreatedate(Date gOtherCreatedate) {
        this.gOtherCreatedate = gOtherCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_name
     *
     * @return the value of groups_other.g_other_name
     *
     * @mbggenerated
     */
    public String getgOtherName() {
        return gOtherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_name
     *
     * @param gOtherName the value for groups_other.g_other_name
     *
     * @mbggenerated
     */
    public void setgOtherName(String gOtherName) {
        this.gOtherName = gOtherName == null ? null : gOtherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_people
     *
     * @return the value of groups_other.g_other_people
     *
     * @mbggenerated
     */
    public Integer getgOtherPeople() {
        return gOtherPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_people
     *
     * @param gOtherPeople the value for groups_other.g_other_people
     *
     * @mbggenerated
     */
    public void setgOtherPeople(Integer gOtherPeople) {
        this.gOtherPeople = gOtherPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_matter
     *
     * @return the value of groups_other.g_other_matter
     *
     * @mbggenerated
     */
    public String getgOtherMatter() {
        return gOtherMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_matter
     *
     * @param gOtherMatter the value for groups_other.g_other_matter
     *
     * @mbggenerated
     */
    public void setgOtherMatter(String gOtherMatter) {
        this.gOtherMatter = gOtherMatter == null ? null : gOtherMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_pay_type_id
     *
     * @return the value of groups_other.g_other_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgOtherPayTypeId() {
        return gOtherPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_pay_type_id
     *
     * @param gOtherPayTypeId the value for groups_other.g_other_pay_type_id
     *
     * @mbggenerated
     */
    public void setgOtherPayTypeId(Integer gOtherPayTypeId) {
        this.gOtherPayTypeId = gOtherPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_sfje
     *
     * @return the value of groups_other.g_other_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgOtherSfje() {
        return gOtherSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_sfje
     *
     * @param gOtherSfje the value for groups_other.g_other_sfje
     *
     * @mbggenerated
     */
    public void setgOtherSfje(BigDecimal gOtherSfje) {
        this.gOtherSfje = gOtherSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_fwf
     *
     * @return the value of groups_other.g_other_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgOtherFwf() {
        return gOtherFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_fwf
     *
     * @param gOtherFwf the value for groups_other.g_other_fwf
     *
     * @mbggenerated
     */
    public void setgOtherFwf(BigDecimal gOtherFwf) {
        this.gOtherFwf = gOtherFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_ssje
     *
     * @return the value of groups_other.g_other_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgOtherSsje() {
        return gOtherSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_ssje
     *
     * @param gOtherSsje the value for groups_other.g_other_ssje
     *
     * @mbggenerated
     */
    public void setgOtherSsje(BigDecimal gOtherSsje) {
        this.gOtherSsje = gOtherSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.g_other_bz
     *
     * @return the value of groups_other.g_other_bz
     *
     * @mbggenerated
     */
    public String getgOtherBz() {
        return gOtherBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.g_other_bz
     *
     * @param gOtherBz the value for groups_other.g_other_bz
     *
     * @mbggenerated
     */
    public void setgOtherBz(String gOtherBz) {
        this.gOtherBz = gOtherBz == null ? null : gOtherBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.createtime
     *
     * @return the value of groups_other.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.createtime
     *
     * @param createtime the value for groups_other.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_other.createuser
     *
     * @return the value of groups_other.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_other.createuser
     *
     * @param createuser the value for groups_other.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}