package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppendOther {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_id
     *
     * @mbggenerated
     */
    private Integer gAOtherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_groups_id
     *
     * @mbggenerated
     */
    private Integer gAOtherGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_createdate
     *
     * @mbggenerated
     */
    private Date gAOtherCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_name
     *
     * @mbggenerated
     */
    private String gAOtherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_people
     *
     * @mbggenerated
     */
    private Integer gAOtherPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_matter
     *
     * @mbggenerated
     */
    private String gAOtherMatter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gAOtherPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gAOtherSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gAOtherFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gAOtherSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.g_a_other_bz
     *
     * @mbggenerated
     */
    private String gAOtherBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_other.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_id
     *
     * @return the value of groups_append_other.g_a_other_id
     *
     * @mbggenerated
     */
    public Integer getgAOtherId() {
        return gAOtherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_id
     *
     * @param gAOtherId the value for groups_append_other.g_a_other_id
     *
     * @mbggenerated
     */
    public void setgAOtherId(Integer gAOtherId) {
        this.gAOtherId = gAOtherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_groups_id
     *
     * @return the value of groups_append_other.g_a_other_groups_id
     *
     * @mbggenerated
     */
    public Integer getgAOtherGroupsId() {
        return gAOtherGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_groups_id
     *
     * @param gAOtherGroupsId the value for groups_append_other.g_a_other_groups_id
     *
     * @mbggenerated
     */
    public void setgAOtherGroupsId(Integer gAOtherGroupsId) {
        this.gAOtherGroupsId = gAOtherGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_createdate
     *
     * @return the value of groups_append_other.g_a_other_createdate
     *
     * @mbggenerated
     */
    public Date getgAOtherCreatedate() {
        return gAOtherCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_createdate
     *
     * @param gAOtherCreatedate the value for groups_append_other.g_a_other_createdate
     *
     * @mbggenerated
     */
    public void setgAOtherCreatedate(Date gAOtherCreatedate) {
        this.gAOtherCreatedate = gAOtherCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_name
     *
     * @return the value of groups_append_other.g_a_other_name
     *
     * @mbggenerated
     */
    public String getgAOtherName() {
        return gAOtherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_name
     *
     * @param gAOtherName the value for groups_append_other.g_a_other_name
     *
     * @mbggenerated
     */
    public void setgAOtherName(String gAOtherName) {
        this.gAOtherName = gAOtherName == null ? null : gAOtherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_people
     *
     * @return the value of groups_append_other.g_a_other_people
     *
     * @mbggenerated
     */
    public Integer getgAOtherPeople() {
        return gAOtherPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_people
     *
     * @param gAOtherPeople the value for groups_append_other.g_a_other_people
     *
     * @mbggenerated
     */
    public void setgAOtherPeople(Integer gAOtherPeople) {
        this.gAOtherPeople = gAOtherPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_matter
     *
     * @return the value of groups_append_other.g_a_other_matter
     *
     * @mbggenerated
     */
    public String getgAOtherMatter() {
        return gAOtherMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_matter
     *
     * @param gAOtherMatter the value for groups_append_other.g_a_other_matter
     *
     * @mbggenerated
     */
    public void setgAOtherMatter(String gAOtherMatter) {
        this.gAOtherMatter = gAOtherMatter == null ? null : gAOtherMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_pay_type_id
     *
     * @return the value of groups_append_other.g_a_other_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgAOtherPayTypeId() {
        return gAOtherPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_pay_type_id
     *
     * @param gAOtherPayTypeId the value for groups_append_other.g_a_other_pay_type_id
     *
     * @mbggenerated
     */
    public void setgAOtherPayTypeId(Integer gAOtherPayTypeId) {
        this.gAOtherPayTypeId = gAOtherPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_sfje
     *
     * @return the value of groups_append_other.g_a_other_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgAOtherSfje() {
        return gAOtherSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_sfje
     *
     * @param gAOtherSfje the value for groups_append_other.g_a_other_sfje
     *
     * @mbggenerated
     */
    public void setgAOtherSfje(BigDecimal gAOtherSfje) {
        this.gAOtherSfje = gAOtherSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_fwf
     *
     * @return the value of groups_append_other.g_a_other_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgAOtherFwf() {
        return gAOtherFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_fwf
     *
     * @param gAOtherFwf the value for groups_append_other.g_a_other_fwf
     *
     * @mbggenerated
     */
    public void setgAOtherFwf(BigDecimal gAOtherFwf) {
        this.gAOtherFwf = gAOtherFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_ssje
     *
     * @return the value of groups_append_other.g_a_other_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgAOtherSsje() {
        return gAOtherSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_ssje
     *
     * @param gAOtherSsje the value for groups_append_other.g_a_other_ssje
     *
     * @mbggenerated
     */
    public void setgAOtherSsje(BigDecimal gAOtherSsje) {
        this.gAOtherSsje = gAOtherSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.g_a_other_bz
     *
     * @return the value of groups_append_other.g_a_other_bz
     *
     * @mbggenerated
     */
    public String getgAOtherBz() {
        return gAOtherBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.g_a_other_bz
     *
     * @param gAOtherBz the value for groups_append_other.g_a_other_bz
     *
     * @mbggenerated
     */
    public void setgAOtherBz(String gAOtherBz) {
        this.gAOtherBz = gAOtherBz == null ? null : gAOtherBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.createtime
     *
     * @return the value of groups_append_other.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.createtime
     *
     * @param createtime the value for groups_append_other.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_other.createuser
     *
     * @return the value of groups_append_other.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_other.createuser
     *
     * @param createuser the value for groups_append_other.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}