package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsHotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_id
     *
     * @mbggenerated
     */
    private Integer gHotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_groups_id
     *
     * @mbggenerated
     */
    private Integer gHotelGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_createdate
     *
     * @mbggenerated
     */
    private Date gHotelCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_name
     *
     * @mbggenerated
     */
    private String gHotelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_rome_type
     *
     * @mbggenerated
     */
    private String gHotelRomeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_people
     *
     * @mbggenerated
     */
    private Integer gHotelPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_date
     *
     * @mbggenerated
     */
    private Date gHotelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_room_night
     *
     * @mbggenerated
     */
    private String gHotelRoomNight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_leave_date
     *
     * @mbggenerated
     */
    private Date gHotelLeaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gHotelPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gHotelSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gHotelFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gHotelSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_skrq
     *
     * @mbggenerated
     */
    private Date gHotelSkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.g_hotel_tkrq
     *
     * @mbggenerated
     */
    private Date gHotelTkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_hotel.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_id
     *
     * @return the value of groups_hotel.g_hotel_id
     *
     * @mbggenerated
     */
    public Integer getgHotelId() {
        return gHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_id
     *
     * @param gHotelId the value for groups_hotel.g_hotel_id
     *
     * @mbggenerated
     */
    public void setgHotelId(Integer gHotelId) {
        this.gHotelId = gHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_groups_id
     *
     * @return the value of groups_hotel.g_hotel_groups_id
     *
     * @mbggenerated
     */
    public Integer getgHotelGroupsId() {
        return gHotelGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_groups_id
     *
     * @param gHotelGroupsId the value for groups_hotel.g_hotel_groups_id
     *
     * @mbggenerated
     */
    public void setgHotelGroupsId(Integer gHotelGroupsId) {
        this.gHotelGroupsId = gHotelGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_createdate
     *
     * @return the value of groups_hotel.g_hotel_createdate
     *
     * @mbggenerated
     */
    public Date getgHotelCreatedate() {
        return gHotelCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_createdate
     *
     * @param gHotelCreatedate the value for groups_hotel.g_hotel_createdate
     *
     * @mbggenerated
     */
    public void setgHotelCreatedate(Date gHotelCreatedate) {
        this.gHotelCreatedate = gHotelCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_name
     *
     * @return the value of groups_hotel.g_hotel_name
     *
     * @mbggenerated
     */
    public String getgHotelName() {
        return gHotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_name
     *
     * @param gHotelName the value for groups_hotel.g_hotel_name
     *
     * @mbggenerated
     */
    public void setgHotelName(String gHotelName) {
        this.gHotelName = gHotelName == null ? null : gHotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_rome_type
     *
     * @return the value of groups_hotel.g_hotel_rome_type
     *
     * @mbggenerated
     */
    public String getgHotelRomeType() {
        return gHotelRomeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_rome_type
     *
     * @param gHotelRomeType the value for groups_hotel.g_hotel_rome_type
     *
     * @mbggenerated
     */
    public void setgHotelRomeType(String gHotelRomeType) {
        this.gHotelRomeType = gHotelRomeType == null ? null : gHotelRomeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_people
     *
     * @return the value of groups_hotel.g_hotel_people
     *
     * @mbggenerated
     */
    public Integer getgHotelPeople() {
        return gHotelPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_people
     *
     * @param gHotelPeople the value for groups_hotel.g_hotel_people
     *
     * @mbggenerated
     */
    public void setgHotelPeople(Integer gHotelPeople) {
        this.gHotelPeople = gHotelPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_date
     *
     * @return the value of groups_hotel.g_hotel_date
     *
     * @mbggenerated
     */
    public Date getgHotelDate() {
        return gHotelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_date
     *
     * @param gHotelDate the value for groups_hotel.g_hotel_date
     *
     * @mbggenerated
     */
    public void setgHotelDate(Date gHotelDate) {
        this.gHotelDate = gHotelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_room_night
     *
     * @return the value of groups_hotel.g_hotel_room_night
     *
     * @mbggenerated
     */
    public String getgHotelRoomNight() {
        return gHotelRoomNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_room_night
     *
     * @param gHotelRoomNight the value for groups_hotel.g_hotel_room_night
     *
     * @mbggenerated
     */
    public void setgHotelRoomNight(String gHotelRoomNight) {
        this.gHotelRoomNight = gHotelRoomNight == null ? null : gHotelRoomNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_leave_date
     *
     * @return the value of groups_hotel.g_hotel_leave_date
     *
     * @mbggenerated
     */
    public Date getgHotelLeaveDate() {
        return gHotelLeaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_leave_date
     *
     * @param gHotelLeaveDate the value for groups_hotel.g_hotel_leave_date
     *
     * @mbggenerated
     */
    public void setgHotelLeaveDate(Date gHotelLeaveDate) {
        this.gHotelLeaveDate = gHotelLeaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_pay_type_id
     *
     * @return the value of groups_hotel.g_hotel_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgHotelPayTypeId() {
        return gHotelPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_pay_type_id
     *
     * @param gHotelPayTypeId the value for groups_hotel.g_hotel_pay_type_id
     *
     * @mbggenerated
     */
    public void setgHotelPayTypeId(Integer gHotelPayTypeId) {
        this.gHotelPayTypeId = gHotelPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_sfje
     *
     * @return the value of groups_hotel.g_hotel_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgHotelSfje() {
        return gHotelSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_sfje
     *
     * @param gHotelSfje the value for groups_hotel.g_hotel_sfje
     *
     * @mbggenerated
     */
    public void setgHotelSfje(BigDecimal gHotelSfje) {
        this.gHotelSfje = gHotelSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_fwf
     *
     * @return the value of groups_hotel.g_hotel_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgHotelFwf() {
        return gHotelFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_fwf
     *
     * @param gHotelFwf the value for groups_hotel.g_hotel_fwf
     *
     * @mbggenerated
     */
    public void setgHotelFwf(BigDecimal gHotelFwf) {
        this.gHotelFwf = gHotelFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_ssje
     *
     * @return the value of groups_hotel.g_hotel_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgHotelSsje() {
        return gHotelSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_ssje
     *
     * @param gHotelSsje the value for groups_hotel.g_hotel_ssje
     *
     * @mbggenerated
     */
    public void setgHotelSsje(BigDecimal gHotelSsje) {
        this.gHotelSsje = gHotelSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_skrq
     *
     * @return the value of groups_hotel.g_hotel_skrq
     *
     * @mbggenerated
     */
    public Date getgHotelSkrq() {
        return gHotelSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_skrq
     *
     * @param gHotelSkrq the value for groups_hotel.g_hotel_skrq
     *
     * @mbggenerated
     */
    public void setgHotelSkrq(Date gHotelSkrq) {
        this.gHotelSkrq = gHotelSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.g_hotel_tkrq
     *
     * @return the value of groups_hotel.g_hotel_tkrq
     *
     * @mbggenerated
     */
    public Date getgHotelTkrq() {
        return gHotelTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.g_hotel_tkrq
     *
     * @param gHotelTkrq the value for groups_hotel.g_hotel_tkrq
     *
     * @mbggenerated
     */
    public void setgHotelTkrq(Date gHotelTkrq) {
        this.gHotelTkrq = gHotelTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.createtime
     *
     * @return the value of groups_hotel.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.createtime
     *
     * @param createtime the value for groups_hotel.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_hotel.createuser
     *
     * @return the value of groups_hotel.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_hotel.createuser
     *
     * @param createuser the value for groups_hotel.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}