package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppendVisa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_id
     *
     * @mbggenerated
     */
    private Integer gAVisaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_groups_id
     *
     * @mbggenerated
     */
    private Integer gAVisaGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_createdate
     *
     * @mbggenerated
     */
    private Date gAVisaCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_name
     *
     * @mbggenerated
     */
    private String gAVisaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_type
     *
     * @mbggenerated
     */
    private String gAVisaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_people
     *
     * @mbggenerated
     */
    private Integer gAVisaPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gAVisaPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gAVisaSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_visa_dj
     *
     * @mbggenerated
     */
    private BigDecimal gAVisaDj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_train_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gATrainFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.g_a_train_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gATrainSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_visa.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_id
     *
     * @return the value of groups_append_visa.g_a_visa_id
     *
     * @mbggenerated
     */
    public Integer getgAVisaId() {
        return gAVisaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_id
     *
     * @param gAVisaId the value for groups_append_visa.g_a_visa_id
     *
     * @mbggenerated
     */
    public void setgAVisaId(Integer gAVisaId) {
        this.gAVisaId = gAVisaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_groups_id
     *
     * @return the value of groups_append_visa.g_a_visa_groups_id
     *
     * @mbggenerated
     */
    public Integer getgAVisaGroupsId() {
        return gAVisaGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_groups_id
     *
     * @param gAVisaGroupsId the value for groups_append_visa.g_a_visa_groups_id
     *
     * @mbggenerated
     */
    public void setgAVisaGroupsId(Integer gAVisaGroupsId) {
        this.gAVisaGroupsId = gAVisaGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_createdate
     *
     * @return the value of groups_append_visa.g_a_visa_createdate
     *
     * @mbggenerated
     */
    public Date getgAVisaCreatedate() {
        return gAVisaCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_createdate
     *
     * @param gAVisaCreatedate the value for groups_append_visa.g_a_visa_createdate
     *
     * @mbggenerated
     */
    public void setgAVisaCreatedate(Date gAVisaCreatedate) {
        this.gAVisaCreatedate = gAVisaCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_name
     *
     * @return the value of groups_append_visa.g_a_visa_name
     *
     * @mbggenerated
     */
    public String getgAVisaName() {
        return gAVisaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_name
     *
     * @param gAVisaName the value for groups_append_visa.g_a_visa_name
     *
     * @mbggenerated
     */
    public void setgAVisaName(String gAVisaName) {
        this.gAVisaName = gAVisaName == null ? null : gAVisaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_type
     *
     * @return the value of groups_append_visa.g_a_visa_type
     *
     * @mbggenerated
     */
    public String getgAVisaType() {
        return gAVisaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_type
     *
     * @param gAVisaType the value for groups_append_visa.g_a_visa_type
     *
     * @mbggenerated
     */
    public void setgAVisaType(String gAVisaType) {
        this.gAVisaType = gAVisaType == null ? null : gAVisaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_people
     *
     * @return the value of groups_append_visa.g_a_visa_people
     *
     * @mbggenerated
     */
    public Integer getgAVisaPeople() {
        return gAVisaPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_people
     *
     * @param gAVisaPeople the value for groups_append_visa.g_a_visa_people
     *
     * @mbggenerated
     */
    public void setgAVisaPeople(Integer gAVisaPeople) {
        this.gAVisaPeople = gAVisaPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_pay_type_id
     *
     * @return the value of groups_append_visa.g_a_visa_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgAVisaPayTypeId() {
        return gAVisaPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_pay_type_id
     *
     * @param gAVisaPayTypeId the value for groups_append_visa.g_a_visa_pay_type_id
     *
     * @mbggenerated
     */
    public void setgAVisaPayTypeId(Integer gAVisaPayTypeId) {
        this.gAVisaPayTypeId = gAVisaPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_sfje
     *
     * @return the value of groups_append_visa.g_a_visa_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgAVisaSfje() {
        return gAVisaSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_sfje
     *
     * @param gAVisaSfje the value for groups_append_visa.g_a_visa_sfje
     *
     * @mbggenerated
     */
    public void setgAVisaSfje(BigDecimal gAVisaSfje) {
        this.gAVisaSfje = gAVisaSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_visa_dj
     *
     * @return the value of groups_append_visa.g_a_visa_dj
     *
     * @mbggenerated
     */
    public BigDecimal getgAVisaDj() {
        return gAVisaDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_visa_dj
     *
     * @param gAVisaDj the value for groups_append_visa.g_a_visa_dj
     *
     * @mbggenerated
     */
    public void setgAVisaDj(BigDecimal gAVisaDj) {
        this.gAVisaDj = gAVisaDj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_train_fwf
     *
     * @return the value of groups_append_visa.g_a_train_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgATrainFwf() {
        return gATrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_train_fwf
     *
     * @param gATrainFwf the value for groups_append_visa.g_a_train_fwf
     *
     * @mbggenerated
     */
    public void setgATrainFwf(BigDecimal gATrainFwf) {
        this.gATrainFwf = gATrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.g_a_train_ssje
     *
     * @return the value of groups_append_visa.g_a_train_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgATrainSsje() {
        return gATrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.g_a_train_ssje
     *
     * @param gATrainSsje the value for groups_append_visa.g_a_train_ssje
     *
     * @mbggenerated
     */
    public void setgATrainSsje(BigDecimal gATrainSsje) {
        this.gATrainSsje = gATrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.createtime
     *
     * @return the value of groups_append_visa.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.createtime
     *
     * @param createtime the value for groups_append_visa.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_visa.createuser
     *
     * @return the value of groups_append_visa.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_visa.createuser
     *
     * @param createuser the value for groups_append_visa.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}