package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppendHotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_id
     *
     * @mbggenerated
     */
    private Integer gAHotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_groups_id
     *
     * @mbggenerated
     */
    private Integer gAHotelGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_createdate
     *
     * @mbggenerated
     */
    private Date gAHotelCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_name
     *
     * @mbggenerated
     */
    private String gAHotelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_rome_type
     *
     * @mbggenerated
     */
    private String gAHotelRomeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_people
     *
     * @mbggenerated
     */
    private Integer gAHotelPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_date
     *
     * @mbggenerated
     */
    private Date gAHotelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_room_night
     *
     * @mbggenerated
     */
    private String gAHotelRoomNight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_leave_date
     *
     * @mbggenerated
     */
    private Date gAHotelLeaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gAHotelPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gAHotelSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gAHotelFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gAHotelSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_skrq
     *
     * @mbggenerated
     */
    private Date gAHotelSkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.g_a_hotel_tkrq
     *
     * @mbggenerated
     */
    private Date gAHotelTkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_hotel.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_id
     *
     * @return the value of groups_append_hotel.g_a_hotel_id
     *
     * @mbggenerated
     */
    public Integer getgAHotelId() {
        return gAHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_id
     *
     * @param gAHotelId the value for groups_append_hotel.g_a_hotel_id
     *
     * @mbggenerated
     */
    public void setgAHotelId(Integer gAHotelId) {
        this.gAHotelId = gAHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_groups_id
     *
     * @return the value of groups_append_hotel.g_a_hotel_groups_id
     *
     * @mbggenerated
     */
    public Integer getgAHotelGroupsId() {
        return gAHotelGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_groups_id
     *
     * @param gAHotelGroupsId the value for groups_append_hotel.g_a_hotel_groups_id
     *
     * @mbggenerated
     */
    public void setgAHotelGroupsId(Integer gAHotelGroupsId) {
        this.gAHotelGroupsId = gAHotelGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_createdate
     *
     * @return the value of groups_append_hotel.g_a_hotel_createdate
     *
     * @mbggenerated
     */
    public Date getgAHotelCreatedate() {
        return gAHotelCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_createdate
     *
     * @param gAHotelCreatedate the value for groups_append_hotel.g_a_hotel_createdate
     *
     * @mbggenerated
     */
    public void setgAHotelCreatedate(Date gAHotelCreatedate) {
        this.gAHotelCreatedate = gAHotelCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_name
     *
     * @return the value of groups_append_hotel.g_a_hotel_name
     *
     * @mbggenerated
     */
    public String getgAHotelName() {
        return gAHotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_name
     *
     * @param gAHotelName the value for groups_append_hotel.g_a_hotel_name
     *
     * @mbggenerated
     */
    public void setgAHotelName(String gAHotelName) {
        this.gAHotelName = gAHotelName == null ? null : gAHotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_rome_type
     *
     * @return the value of groups_append_hotel.g_a_hotel_rome_type
     *
     * @mbggenerated
     */
    public String getgAHotelRomeType() {
        return gAHotelRomeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_rome_type
     *
     * @param gAHotelRomeType the value for groups_append_hotel.g_a_hotel_rome_type
     *
     * @mbggenerated
     */
    public void setgAHotelRomeType(String gAHotelRomeType) {
        this.gAHotelRomeType = gAHotelRomeType == null ? null : gAHotelRomeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_people
     *
     * @return the value of groups_append_hotel.g_a_hotel_people
     *
     * @mbggenerated
     */
    public Integer getgAHotelPeople() {
        return gAHotelPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_people
     *
     * @param gAHotelPeople the value for groups_append_hotel.g_a_hotel_people
     *
     * @mbggenerated
     */
    public void setgAHotelPeople(Integer gAHotelPeople) {
        this.gAHotelPeople = gAHotelPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_date
     *
     * @return the value of groups_append_hotel.g_a_hotel_date
     *
     * @mbggenerated
     */
    public Date getgAHotelDate() {
        return gAHotelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_date
     *
     * @param gAHotelDate the value for groups_append_hotel.g_a_hotel_date
     *
     * @mbggenerated
     */
    public void setgAHotelDate(Date gAHotelDate) {
        this.gAHotelDate = gAHotelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_room_night
     *
     * @return the value of groups_append_hotel.g_a_hotel_room_night
     *
     * @mbggenerated
     */
    public String getgAHotelRoomNight() {
        return gAHotelRoomNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_room_night
     *
     * @param gAHotelRoomNight the value for groups_append_hotel.g_a_hotel_room_night
     *
     * @mbggenerated
     */
    public void setgAHotelRoomNight(String gAHotelRoomNight) {
        this.gAHotelRoomNight = gAHotelRoomNight == null ? null : gAHotelRoomNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_leave_date
     *
     * @return the value of groups_append_hotel.g_a_hotel_leave_date
     *
     * @mbggenerated
     */
    public Date getgAHotelLeaveDate() {
        return gAHotelLeaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_leave_date
     *
     * @param gAHotelLeaveDate the value for groups_append_hotel.g_a_hotel_leave_date
     *
     * @mbggenerated
     */
    public void setgAHotelLeaveDate(Date gAHotelLeaveDate) {
        this.gAHotelLeaveDate = gAHotelLeaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_pay_type_id
     *
     * @return the value of groups_append_hotel.g_a_hotel_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgAHotelPayTypeId() {
        return gAHotelPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_pay_type_id
     *
     * @param gAHotelPayTypeId the value for groups_append_hotel.g_a_hotel_pay_type_id
     *
     * @mbggenerated
     */
    public void setgAHotelPayTypeId(Integer gAHotelPayTypeId) {
        this.gAHotelPayTypeId = gAHotelPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_sfje
     *
     * @return the value of groups_append_hotel.g_a_hotel_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgAHotelSfje() {
        return gAHotelSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_sfje
     *
     * @param gAHotelSfje the value for groups_append_hotel.g_a_hotel_sfje
     *
     * @mbggenerated
     */
    public void setgAHotelSfje(BigDecimal gAHotelSfje) {
        this.gAHotelSfje = gAHotelSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_fwf
     *
     * @return the value of groups_append_hotel.g_a_hotel_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgAHotelFwf() {
        return gAHotelFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_fwf
     *
     * @param gAHotelFwf the value for groups_append_hotel.g_a_hotel_fwf
     *
     * @mbggenerated
     */
    public void setgAHotelFwf(BigDecimal gAHotelFwf) {
        this.gAHotelFwf = gAHotelFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_ssje
     *
     * @return the value of groups_append_hotel.g_a_hotel_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgAHotelSsje() {
        return gAHotelSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_ssje
     *
     * @param gAHotelSsje the value for groups_append_hotel.g_a_hotel_ssje
     *
     * @mbggenerated
     */
    public void setgAHotelSsje(BigDecimal gAHotelSsje) {
        this.gAHotelSsje = gAHotelSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_skrq
     *
     * @return the value of groups_append_hotel.g_a_hotel_skrq
     *
     * @mbggenerated
     */
    public Date getgAHotelSkrq() {
        return gAHotelSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_skrq
     *
     * @param gAHotelSkrq the value for groups_append_hotel.g_a_hotel_skrq
     *
     * @mbggenerated
     */
    public void setgAHotelSkrq(Date gAHotelSkrq) {
        this.gAHotelSkrq = gAHotelSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.g_a_hotel_tkrq
     *
     * @return the value of groups_append_hotel.g_a_hotel_tkrq
     *
     * @mbggenerated
     */
    public Date getgAHotelTkrq() {
        return gAHotelTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.g_a_hotel_tkrq
     *
     * @param gAHotelTkrq the value for groups_append_hotel.g_a_hotel_tkrq
     *
     * @mbggenerated
     */
    public void setgAHotelTkrq(Date gAHotelTkrq) {
        this.gAHotelTkrq = gAHotelTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.createtime
     *
     * @return the value of groups_append_hotel.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.createtime
     *
     * @param createtime the value for groups_append_hotel.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_hotel.createuser
     *
     * @return the value of groups_append_hotel.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_hotel.createuser
     *
     * @param createuser the value for groups_append_hotel.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}