package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Groups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_id
     *
     * @mbggenerated
     */
    private Integer groupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_name
     *
     * @mbggenerated
     */
    private String groupsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_sfje
     *
     * @mbggenerated
     */
    private BigDecimal groupsSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_jpfl
     *
     * @mbggenerated
     */
    private BigDecimal groupsJpfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_fwf
     *
     * @mbggenerated
     */
    private BigDecimal groupsFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_ssje
     *
     * @mbggenerated
     */
    private BigDecimal groupsSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groups_status
     *
     * @mbggenerated
     */
    private Integer groupsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_id
     *
     * @return the value of groups.groups_id
     *
     * @mbggenerated
     */
    public Integer getGroupsId() {
        return groupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_id
     *
     * @param groupsId the value for groups.groups_id
     *
     * @mbggenerated
     */
    public void setGroupsId(Integer groupsId) {
        this.groupsId = groupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_name
     *
     * @return the value of groups.groups_name
     *
     * @mbggenerated
     */
    public String getGroupsName() {
        return groupsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_name
     *
     * @param groupsName the value for groups.groups_name
     *
     * @mbggenerated
     */
    public void setGroupsName(String groupsName) {
        this.groupsName = groupsName == null ? null : groupsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_sfje
     *
     * @return the value of groups.groups_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getGroupsSfje() {
        return groupsSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_sfje
     *
     * @param groupsSfje the value for groups.groups_sfje
     *
     * @mbggenerated
     */
    public void setGroupsSfje(BigDecimal groupsSfje) {
        this.groupsSfje = groupsSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_jpfl
     *
     * @return the value of groups.groups_jpfl
     *
     * @mbggenerated
     */
    public BigDecimal getGroupsJpfl() {
        return groupsJpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_jpfl
     *
     * @param groupsJpfl the value for groups.groups_jpfl
     *
     * @mbggenerated
     */
    public void setGroupsJpfl(BigDecimal groupsJpfl) {
        this.groupsJpfl = groupsJpfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_fwf
     *
     * @return the value of groups.groups_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getGroupsFwf() {
        return groupsFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_fwf
     *
     * @param groupsFwf the value for groups.groups_fwf
     *
     * @mbggenerated
     */
    public void setGroupsFwf(BigDecimal groupsFwf) {
        this.groupsFwf = groupsFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_ssje
     *
     * @return the value of groups.groups_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getGroupsSsje() {
        return groupsSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_ssje
     *
     * @param groupsSsje the value for groups.groups_ssje
     *
     * @mbggenerated
     */
    public void setGroupsSsje(BigDecimal groupsSsje) {
        this.groupsSsje = groupsSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groups_status
     *
     * @return the value of groups.groups_status
     *
     * @mbggenerated
     */
    public Integer getGroupsStatus() {
        return groupsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groups_status
     *
     * @param groupsStatus the value for groups.groups_status
     *
     * @mbggenerated
     */
    public void setGroupsStatus(Integer groupsStatus) {
        this.groupsStatus = groupsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.createtime
     *
     * @return the value of groups.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.createtime
     *
     * @param createtime the value for groups.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.createuser
     *
     * @return the value of groups.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.createuser
     *
     * @param createuser the value for groups.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}