package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppendCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_id
     *
     * @mbggenerated
     */
    private Integer gACarId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_groups_id
     *
     * @mbggenerated
     */
    private Integer gACarGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_createdate
     *
     * @mbggenerated
     */
    private Date gACarCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_name
     *
     * @mbggenerated
     */
    private String gACarName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_type
     *
     * @mbggenerated
     */
    private String gACarType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_people
     *
     * @mbggenerated
     */
    private Integer gACarPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_count
     *
     * @mbggenerated
     */
    private Integer gACarCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gACarPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gACarSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gACarFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.g_a_car_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gACarSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_car.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_id
     *
     * @return the value of groups_append_car.g_a_car_id
     *
     * @mbggenerated
     */
    public Integer getgACarId() {
        return gACarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_id
     *
     * @param gACarId the value for groups_append_car.g_a_car_id
     *
     * @mbggenerated
     */
    public void setgACarId(Integer gACarId) {
        this.gACarId = gACarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_groups_id
     *
     * @return the value of groups_append_car.g_a_car_groups_id
     *
     * @mbggenerated
     */
    public Integer getgACarGroupsId() {
        return gACarGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_groups_id
     *
     * @param gACarGroupsId the value for groups_append_car.g_a_car_groups_id
     *
     * @mbggenerated
     */
    public void setgACarGroupsId(Integer gACarGroupsId) {
        this.gACarGroupsId = gACarGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_createdate
     *
     * @return the value of groups_append_car.g_a_car_createdate
     *
     * @mbggenerated
     */
    public Date getgACarCreatedate() {
        return gACarCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_createdate
     *
     * @param gACarCreatedate the value for groups_append_car.g_a_car_createdate
     *
     * @mbggenerated
     */
    public void setgACarCreatedate(Date gACarCreatedate) {
        this.gACarCreatedate = gACarCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_name
     *
     * @return the value of groups_append_car.g_a_car_name
     *
     * @mbggenerated
     */
    public String getgACarName() {
        return gACarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_name
     *
     * @param gACarName the value for groups_append_car.g_a_car_name
     *
     * @mbggenerated
     */
    public void setgACarName(String gACarName) {
        this.gACarName = gACarName == null ? null : gACarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_type
     *
     * @return the value of groups_append_car.g_a_car_type
     *
     * @mbggenerated
     */
    public String getgACarType() {
        return gACarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_type
     *
     * @param gACarType the value for groups_append_car.g_a_car_type
     *
     * @mbggenerated
     */
    public void setgACarType(String gACarType) {
        this.gACarType = gACarType == null ? null : gACarType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_people
     *
     * @return the value of groups_append_car.g_a_car_people
     *
     * @mbggenerated
     */
    public Integer getgACarPeople() {
        return gACarPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_people
     *
     * @param gACarPeople the value for groups_append_car.g_a_car_people
     *
     * @mbggenerated
     */
    public void setgACarPeople(Integer gACarPeople) {
        this.gACarPeople = gACarPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_count
     *
     * @return the value of groups_append_car.g_a_car_count
     *
     * @mbggenerated
     */
    public Integer getgACarCount() {
        return gACarCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_count
     *
     * @param gACarCount the value for groups_append_car.g_a_car_count
     *
     * @mbggenerated
     */
    public void setgACarCount(Integer gACarCount) {
        this.gACarCount = gACarCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_pay_type_id
     *
     * @return the value of groups_append_car.g_a_car_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgACarPayTypeId() {
        return gACarPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_pay_type_id
     *
     * @param gACarPayTypeId the value for groups_append_car.g_a_car_pay_type_id
     *
     * @mbggenerated
     */
    public void setgACarPayTypeId(Integer gACarPayTypeId) {
        this.gACarPayTypeId = gACarPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_sfje
     *
     * @return the value of groups_append_car.g_a_car_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgACarSfje() {
        return gACarSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_sfje
     *
     * @param gACarSfje the value for groups_append_car.g_a_car_sfje
     *
     * @mbggenerated
     */
    public void setgACarSfje(BigDecimal gACarSfje) {
        this.gACarSfje = gACarSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_fwf
     *
     * @return the value of groups_append_car.g_a_car_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgACarFwf() {
        return gACarFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_fwf
     *
     * @param gACarFwf the value for groups_append_car.g_a_car_fwf
     *
     * @mbggenerated
     */
    public void setgACarFwf(BigDecimal gACarFwf) {
        this.gACarFwf = gACarFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.g_a_car_ssje
     *
     * @return the value of groups_append_car.g_a_car_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgACarSsje() {
        return gACarSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.g_a_car_ssje
     *
     * @param gACarSsje the value for groups_append_car.g_a_car_ssje
     *
     * @mbggenerated
     */
    public void setgACarSsje(BigDecimal gACarSsje) {
        this.gACarSsje = gACarSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.createtime
     *
     * @return the value of groups_append_car.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.createtime
     *
     * @param createtime the value for groups_append_car.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_car.createuser
     *
     * @return the value of groups_append_car.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_car.createuser
     *
     * @param createuser the value for groups_append_car.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}