package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppendTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_id
     *
     * @mbggenerated
     */
    private Integer gATicketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_groups_id
     *
     * @mbggenerated
     */
    private Integer gATicketGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_createdate
     *
     * @mbggenerated
     */
    private Date gATicketCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_booker
     *
     * @mbggenerated
     */
    private String gATicketBooker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_passenger
     *
     * @mbggenerated
     */
    private String gATicketPassenger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_orderno
     *
     * @mbggenerated
     */
    private String gATicketOrderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_pnr
     *
     * @mbggenerated
     */
    private String gATicketPnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_cw
     *
     * @mbggenerated
     */
    private String gATicketCw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_ph
     *
     * @mbggenerated
     */
    private String gATicketPh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_from
     *
     * @mbggenerated
     */
    private String gATicketFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_to
     *
     * @mbggenerated
     */
    private String gATicketTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_date
     *
     * @mbggenerated
     */
    private Date gATicketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_no
     *
     * @mbggenerated
     */
    private String gATicketNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gATicketPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gATicketSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_pmje
     *
     * @mbggenerated
     */
    private BigDecimal gATicketPmje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_sf
     *
     * @mbggenerated
     */
    private BigDecimal gATicketSf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gATicketSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_fl
     *
     * @mbggenerated
     */
    private BigDecimal gATicketFl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_lr
     *
     * @mbggenerated
     */
    private BigDecimal gATicketLr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_skrq
     *
     * @mbggenerated
     */
    private Date gATicketSkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_tkrq
     *
     * @mbggenerated
     */
    private Date gATicketTkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_bz
     *
     * @mbggenerated
     */
    private String gATicketBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.g_a_ticket_ssr
     *
     * @mbggenerated
     */
    private String gATicketSsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_ticket.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_id
     *
     * @return the value of groups_append_ticket.g_a_ticket_id
     *
     * @mbggenerated
     */
    public Integer getgATicketId() {
        return gATicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_id
     *
     * @param gATicketId the value for groups_append_ticket.g_a_ticket_id
     *
     * @mbggenerated
     */
    public void setgATicketId(Integer gATicketId) {
        this.gATicketId = gATicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_groups_id
     *
     * @return the value of groups_append_ticket.g_a_ticket_groups_id
     *
     * @mbggenerated
     */
    public Integer getgATicketGroupsId() {
        return gATicketGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_groups_id
     *
     * @param gATicketGroupsId the value for groups_append_ticket.g_a_ticket_groups_id
     *
     * @mbggenerated
     */
    public void setgATicketGroupsId(Integer gATicketGroupsId) {
        this.gATicketGroupsId = gATicketGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_createdate
     *
     * @return the value of groups_append_ticket.g_a_ticket_createdate
     *
     * @mbggenerated
     */
    public Date getgATicketCreatedate() {
        return gATicketCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_createdate
     *
     * @param gATicketCreatedate the value for groups_append_ticket.g_a_ticket_createdate
     *
     * @mbggenerated
     */
    public void setgATicketCreatedate(Date gATicketCreatedate) {
        this.gATicketCreatedate = gATicketCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_booker
     *
     * @return the value of groups_append_ticket.g_a_ticket_booker
     *
     * @mbggenerated
     */
    public String getgATicketBooker() {
        return gATicketBooker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_booker
     *
     * @param gATicketBooker the value for groups_append_ticket.g_a_ticket_booker
     *
     * @mbggenerated
     */
    public void setgATicketBooker(String gATicketBooker) {
        this.gATicketBooker = gATicketBooker == null ? null : gATicketBooker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_passenger
     *
     * @return the value of groups_append_ticket.g_a_ticket_passenger
     *
     * @mbggenerated
     */
    public String getgATicketPassenger() {
        return gATicketPassenger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_passenger
     *
     * @param gATicketPassenger the value for groups_append_ticket.g_a_ticket_passenger
     *
     * @mbggenerated
     */
    public void setgATicketPassenger(String gATicketPassenger) {
        this.gATicketPassenger = gATicketPassenger == null ? null : gATicketPassenger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_orderno
     *
     * @return the value of groups_append_ticket.g_a_ticket_orderno
     *
     * @mbggenerated
     */
    public String getgATicketOrderno() {
        return gATicketOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_orderno
     *
     * @param gATicketOrderno the value for groups_append_ticket.g_a_ticket_orderno
     *
     * @mbggenerated
     */
    public void setgATicketOrderno(String gATicketOrderno) {
        this.gATicketOrderno = gATicketOrderno == null ? null : gATicketOrderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_pnr
     *
     * @return the value of groups_append_ticket.g_a_ticket_pnr
     *
     * @mbggenerated
     */
    public String getgATicketPnr() {
        return gATicketPnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_pnr
     *
     * @param gATicketPnr the value for groups_append_ticket.g_a_ticket_pnr
     *
     * @mbggenerated
     */
    public void setgATicketPnr(String gATicketPnr) {
        this.gATicketPnr = gATicketPnr == null ? null : gATicketPnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_cw
     *
     * @return the value of groups_append_ticket.g_a_ticket_cw
     *
     * @mbggenerated
     */
    public String getgATicketCw() {
        return gATicketCw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_cw
     *
     * @param gATicketCw the value for groups_append_ticket.g_a_ticket_cw
     *
     * @mbggenerated
     */
    public void setgATicketCw(String gATicketCw) {
        this.gATicketCw = gATicketCw == null ? null : gATicketCw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_ph
     *
     * @return the value of groups_append_ticket.g_a_ticket_ph
     *
     * @mbggenerated
     */
    public String getgATicketPh() {
        return gATicketPh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_ph
     *
     * @param gATicketPh the value for groups_append_ticket.g_a_ticket_ph
     *
     * @mbggenerated
     */
    public void setgATicketPh(String gATicketPh) {
        this.gATicketPh = gATicketPh == null ? null : gATicketPh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_from
     *
     * @return the value of groups_append_ticket.g_a_ticket_from
     *
     * @mbggenerated
     */
    public String getgATicketFrom() {
        return gATicketFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_from
     *
     * @param gATicketFrom the value for groups_append_ticket.g_a_ticket_from
     *
     * @mbggenerated
     */
    public void setgATicketFrom(String gATicketFrom) {
        this.gATicketFrom = gATicketFrom == null ? null : gATicketFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_to
     *
     * @return the value of groups_append_ticket.g_a_ticket_to
     *
     * @mbggenerated
     */
    public String getgATicketTo() {
        return gATicketTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_to
     *
     * @param gATicketTo the value for groups_append_ticket.g_a_ticket_to
     *
     * @mbggenerated
     */
    public void setgATicketTo(String gATicketTo) {
        this.gATicketTo = gATicketTo == null ? null : gATicketTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_date
     *
     * @return the value of groups_append_ticket.g_a_ticket_date
     *
     * @mbggenerated
     */
    public Date getgATicketDate() {
        return gATicketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_date
     *
     * @param gATicketDate the value for groups_append_ticket.g_a_ticket_date
     *
     * @mbggenerated
     */
    public void setgATicketDate(Date gATicketDate) {
        this.gATicketDate = gATicketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_no
     *
     * @return the value of groups_append_ticket.g_a_ticket_no
     *
     * @mbggenerated
     */
    public String getgATicketNo() {
        return gATicketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_no
     *
     * @param gATicketNo the value for groups_append_ticket.g_a_ticket_no
     *
     * @mbggenerated
     */
    public void setgATicketNo(String gATicketNo) {
        this.gATicketNo = gATicketNo == null ? null : gATicketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_pay_type_id
     *
     * @return the value of groups_append_ticket.g_a_ticket_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgATicketPayTypeId() {
        return gATicketPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_pay_type_id
     *
     * @param gATicketPayTypeId the value for groups_append_ticket.g_a_ticket_pay_type_id
     *
     * @mbggenerated
     */
    public void setgATicketPayTypeId(Integer gATicketPayTypeId) {
        this.gATicketPayTypeId = gATicketPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_sfje
     *
     * @return the value of groups_append_ticket.g_a_ticket_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgATicketSfje() {
        return gATicketSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_sfje
     *
     * @param gATicketSfje the value for groups_append_ticket.g_a_ticket_sfje
     *
     * @mbggenerated
     */
    public void setgATicketSfje(BigDecimal gATicketSfje) {
        this.gATicketSfje = gATicketSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_pmje
     *
     * @return the value of groups_append_ticket.g_a_ticket_pmje
     *
     * @mbggenerated
     */
    public BigDecimal getgATicketPmje() {
        return gATicketPmje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_pmje
     *
     * @param gATicketPmje the value for groups_append_ticket.g_a_ticket_pmje
     *
     * @mbggenerated
     */
    public void setgATicketPmje(BigDecimal gATicketPmje) {
        this.gATicketPmje = gATicketPmje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_sf
     *
     * @return the value of groups_append_ticket.g_a_ticket_sf
     *
     * @mbggenerated
     */
    public BigDecimal getgATicketSf() {
        return gATicketSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_sf
     *
     * @param gATicketSf the value for groups_append_ticket.g_a_ticket_sf
     *
     * @mbggenerated
     */
    public void setgATicketSf(BigDecimal gATicketSf) {
        this.gATicketSf = gATicketSf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_ssje
     *
     * @return the value of groups_append_ticket.g_a_ticket_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgATicketSsje() {
        return gATicketSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_ssje
     *
     * @param gATicketSsje the value for groups_append_ticket.g_a_ticket_ssje
     *
     * @mbggenerated
     */
    public void setgATicketSsje(BigDecimal gATicketSsje) {
        this.gATicketSsje = gATicketSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_fl
     *
     * @return the value of groups_append_ticket.g_a_ticket_fl
     *
     * @mbggenerated
     */
    public BigDecimal getgATicketFl() {
        return gATicketFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_fl
     *
     * @param gATicketFl the value for groups_append_ticket.g_a_ticket_fl
     *
     * @mbggenerated
     */
    public void setgATicketFl(BigDecimal gATicketFl) {
        this.gATicketFl = gATicketFl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_lr
     *
     * @return the value of groups_append_ticket.g_a_ticket_lr
     *
     * @mbggenerated
     */
    public BigDecimal getgATicketLr() {
        return gATicketLr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_lr
     *
     * @param gATicketLr the value for groups_append_ticket.g_a_ticket_lr
     *
     * @mbggenerated
     */
    public void setgATicketLr(BigDecimal gATicketLr) {
        this.gATicketLr = gATicketLr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_skrq
     *
     * @return the value of groups_append_ticket.g_a_ticket_skrq
     *
     * @mbggenerated
     */
    public Date getgATicketSkrq() {
        return gATicketSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_skrq
     *
     * @param gATicketSkrq the value for groups_append_ticket.g_a_ticket_skrq
     *
     * @mbggenerated
     */
    public void setgATicketSkrq(Date gATicketSkrq) {
        this.gATicketSkrq = gATicketSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_tkrq
     *
     * @return the value of groups_append_ticket.g_a_ticket_tkrq
     *
     * @mbggenerated
     */
    public Date getgATicketTkrq() {
        return gATicketTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_tkrq
     *
     * @param gATicketTkrq the value for groups_append_ticket.g_a_ticket_tkrq
     *
     * @mbggenerated
     */
    public void setgATicketTkrq(Date gATicketTkrq) {
        this.gATicketTkrq = gATicketTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_bz
     *
     * @return the value of groups_append_ticket.g_a_ticket_bz
     *
     * @mbggenerated
     */
    public String getgATicketBz() {
        return gATicketBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_bz
     *
     * @param gATicketBz the value for groups_append_ticket.g_a_ticket_bz
     *
     * @mbggenerated
     */
    public void setgATicketBz(String gATicketBz) {
        this.gATicketBz = gATicketBz == null ? null : gATicketBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.g_a_ticket_ssr
     *
     * @return the value of groups_append_ticket.g_a_ticket_ssr
     *
     * @mbggenerated
     */
    public String getgATicketSsr() {
        return gATicketSsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.g_a_ticket_ssr
     *
     * @param gATicketSsr the value for groups_append_ticket.g_a_ticket_ssr
     *
     * @mbggenerated
     */
    public void setgATicketSsr(String gATicketSsr) {
        this.gATicketSsr = gATicketSsr == null ? null : gATicketSsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.createtime
     *
     * @return the value of groups_append_ticket.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.createtime
     *
     * @param createtime the value for groups_append_ticket.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_ticket.createuser
     *
     * @return the value of groups_append_ticket.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_ticket.createuser
     *
     * @param createuser the value for groups_append_ticket.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}