package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupsAppendTrain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_id
     *
     * @mbggenerated
     */
    private Integer gATrainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_groups_id
     *
     * @mbggenerated
     */
    private Integer gATrainGroupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_createdate
     *
     * @mbggenerated
     */
    private Date gATrainCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_name
     *
     * @mbggenerated
     */
    private String gATrainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_orderno
     *
     * @mbggenerated
     */
    private String gATrainOrderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_xb
     *
     * @mbggenerated
     */
    private String gATrainXb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_from
     *
     * @mbggenerated
     */
    private String gATrainFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_to
     *
     * @mbggenerated
     */
    private String gATrainTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_start_date
     *
     * @mbggenerated
     */
    private Date gATrainStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_number
     *
     * @mbggenerated
     */
    private String gATrainNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_pay_type_id
     *
     * @mbggenerated
     */
    private Integer gATrainPayTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_sfje
     *
     * @mbggenerated
     */
    private BigDecimal gATrainSfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_fwf
     *
     * @mbggenerated
     */
    private BigDecimal gATrainFwf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_ssje
     *
     * @mbggenerated
     */
    private BigDecimal gATrainSsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_skrq
     *
     * @mbggenerated
     */
    private Date gATrainSkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.g_a_train_tkrq
     *
     * @mbggenerated
     */
    private Date gATrainTkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups_append_train.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_id
     *
     * @return the value of groups_append_train.g_a_train_id
     *
     * @mbggenerated
     */
    public Integer getgATrainId() {
        return gATrainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_id
     *
     * @param gATrainId the value for groups_append_train.g_a_train_id
     *
     * @mbggenerated
     */
    public void setgATrainId(Integer gATrainId) {
        this.gATrainId = gATrainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_groups_id
     *
     * @return the value of groups_append_train.g_a_train_groups_id
     *
     * @mbggenerated
     */
    public Integer getgATrainGroupsId() {
        return gATrainGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_groups_id
     *
     * @param gATrainGroupsId the value for groups_append_train.g_a_train_groups_id
     *
     * @mbggenerated
     */
    public void setgATrainGroupsId(Integer gATrainGroupsId) {
        this.gATrainGroupsId = gATrainGroupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_createdate
     *
     * @return the value of groups_append_train.g_a_train_createdate
     *
     * @mbggenerated
     */
    public Date getgATrainCreatedate() {
        return gATrainCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_createdate
     *
     * @param gATrainCreatedate the value for groups_append_train.g_a_train_createdate
     *
     * @mbggenerated
     */
    public void setgATrainCreatedate(Date gATrainCreatedate) {
        this.gATrainCreatedate = gATrainCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_name
     *
     * @return the value of groups_append_train.g_a_train_name
     *
     * @mbggenerated
     */
    public String getgATrainName() {
        return gATrainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_name
     *
     * @param gATrainName the value for groups_append_train.g_a_train_name
     *
     * @mbggenerated
     */
    public void setgATrainName(String gATrainName) {
        this.gATrainName = gATrainName == null ? null : gATrainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_orderno
     *
     * @return the value of groups_append_train.g_a_train_orderno
     *
     * @mbggenerated
     */
    public String getgATrainOrderno() {
        return gATrainOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_orderno
     *
     * @param gATrainOrderno the value for groups_append_train.g_a_train_orderno
     *
     * @mbggenerated
     */
    public void setgATrainOrderno(String gATrainOrderno) {
        this.gATrainOrderno = gATrainOrderno == null ? null : gATrainOrderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_xb
     *
     * @return the value of groups_append_train.g_a_train_xb
     *
     * @mbggenerated
     */
    public String getgATrainXb() {
        return gATrainXb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_xb
     *
     * @param gATrainXb the value for groups_append_train.g_a_train_xb
     *
     * @mbggenerated
     */
    public void setgATrainXb(String gATrainXb) {
        this.gATrainXb = gATrainXb == null ? null : gATrainXb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_from
     *
     * @return the value of groups_append_train.g_a_train_from
     *
     * @mbggenerated
     */
    public String getgATrainFrom() {
        return gATrainFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_from
     *
     * @param gATrainFrom the value for groups_append_train.g_a_train_from
     *
     * @mbggenerated
     */
    public void setgATrainFrom(String gATrainFrom) {
        this.gATrainFrom = gATrainFrom == null ? null : gATrainFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_to
     *
     * @return the value of groups_append_train.g_a_train_to
     *
     * @mbggenerated
     */
    public String getgATrainTo() {
        return gATrainTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_to
     *
     * @param gATrainTo the value for groups_append_train.g_a_train_to
     *
     * @mbggenerated
     */
    public void setgATrainTo(String gATrainTo) {
        this.gATrainTo = gATrainTo == null ? null : gATrainTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_start_date
     *
     * @return the value of groups_append_train.g_a_train_start_date
     *
     * @mbggenerated
     */
    public Date getgATrainStartDate() {
        return gATrainStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_start_date
     *
     * @param gATrainStartDate the value for groups_append_train.g_a_train_start_date
     *
     * @mbggenerated
     */
    public void setgATrainStartDate(Date gATrainStartDate) {
        this.gATrainStartDate = gATrainStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_number
     *
     * @return the value of groups_append_train.g_a_train_number
     *
     * @mbggenerated
     */
    public String getgATrainNumber() {
        return gATrainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_number
     *
     * @param gATrainNumber the value for groups_append_train.g_a_train_number
     *
     * @mbggenerated
     */
    public void setgATrainNumber(String gATrainNumber) {
        this.gATrainNumber = gATrainNumber == null ? null : gATrainNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_pay_type_id
     *
     * @return the value of groups_append_train.g_a_train_pay_type_id
     *
     * @mbggenerated
     */
    public Integer getgATrainPayTypeId() {
        return gATrainPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_pay_type_id
     *
     * @param gATrainPayTypeId the value for groups_append_train.g_a_train_pay_type_id
     *
     * @mbggenerated
     */
    public void setgATrainPayTypeId(Integer gATrainPayTypeId) {
        this.gATrainPayTypeId = gATrainPayTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_sfje
     *
     * @return the value of groups_append_train.g_a_train_sfje
     *
     * @mbggenerated
     */
    public BigDecimal getgATrainSfje() {
        return gATrainSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_sfje
     *
     * @param gATrainSfje the value for groups_append_train.g_a_train_sfje
     *
     * @mbggenerated
     */
    public void setgATrainSfje(BigDecimal gATrainSfje) {
        this.gATrainSfje = gATrainSfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_fwf
     *
     * @return the value of groups_append_train.g_a_train_fwf
     *
     * @mbggenerated
     */
    public BigDecimal getgATrainFwf() {
        return gATrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_fwf
     *
     * @param gATrainFwf the value for groups_append_train.g_a_train_fwf
     *
     * @mbggenerated
     */
    public void setgATrainFwf(BigDecimal gATrainFwf) {
        this.gATrainFwf = gATrainFwf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_ssje
     *
     * @return the value of groups_append_train.g_a_train_ssje
     *
     * @mbggenerated
     */
    public BigDecimal getgATrainSsje() {
        return gATrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_ssje
     *
     * @param gATrainSsje the value for groups_append_train.g_a_train_ssje
     *
     * @mbggenerated
     */
    public void setgATrainSsje(BigDecimal gATrainSsje) {
        this.gATrainSsje = gATrainSsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_skrq
     *
     * @return the value of groups_append_train.g_a_train_skrq
     *
     * @mbggenerated
     */
    public Date getgATrainSkrq() {
        return gATrainSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_skrq
     *
     * @param gATrainSkrq the value for groups_append_train.g_a_train_skrq
     *
     * @mbggenerated
     */
    public void setgATrainSkrq(Date gATrainSkrq) {
        this.gATrainSkrq = gATrainSkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.g_a_train_tkrq
     *
     * @return the value of groups_append_train.g_a_train_tkrq
     *
     * @mbggenerated
     */
    public Date getgATrainTkrq() {
        return gATrainTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.g_a_train_tkrq
     *
     * @param gATrainTkrq the value for groups_append_train.g_a_train_tkrq
     *
     * @mbggenerated
     */
    public void setgATrainTkrq(Date gATrainTkrq) {
        this.gATrainTkrq = gATrainTkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.createtime
     *
     * @return the value of groups_append_train.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.createtime
     *
     * @param createtime the value for groups_append_train.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups_append_train.createuser
     *
     * @return the value of groups_append_train.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups_append_train.createuser
     *
     * @param createuser the value for groups_append_train.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}