package com.wwl.entity;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_id
     *
     * @mbggenerated
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_code
     *
     * @mbggenerated
     */
    private String mCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_name
     *
     * @mbggenerated
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_sort
     *
     * @mbggenerated
     */
    private Integer mSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_desc
     *
     * @mbggenerated
     */
    private String mDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_depth
     *
     * @mbggenerated
     */
    private Integer mDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_parent
     *
     * @mbggenerated
     */
    private String mParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_count
     *
     * @mbggenerated
     */
    private Integer mCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_id
     *
     * @return the value of menu.m_id
     *
     * @mbggenerated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_id
     *
     * @param mId the value for menu.m_id
     *
     * @mbggenerated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_code
     *
     * @return the value of menu.m_code
     *
     * @mbggenerated
     */
    public String getmCode() {
        return mCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_code
     *
     * @param mCode the value for menu.m_code
     *
     * @mbggenerated
     */
    public void setmCode(String mCode) {
        this.mCode = mCode == null ? null : mCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_name
     *
     * @return the value of menu.m_name
     *
     * @mbggenerated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_name
     *
     * @param mName the value for menu.m_name
     *
     * @mbggenerated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_sort
     *
     * @return the value of menu.m_sort
     *
     * @mbggenerated
     */
    public Integer getmSort() {
        return mSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_sort
     *
     * @param mSort the value for menu.m_sort
     *
     * @mbggenerated
     */
    public void setmSort(Integer mSort) {
        this.mSort = mSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_desc
     *
     * @return the value of menu.m_desc
     *
     * @mbggenerated
     */
    public String getmDesc() {
        return mDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_desc
     *
     * @param mDesc the value for menu.m_desc
     *
     * @mbggenerated
     */
    public void setmDesc(String mDesc) {
        this.mDesc = mDesc == null ? null : mDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_depth
     *
     * @return the value of menu.m_depth
     *
     * @mbggenerated
     */
    public Integer getmDepth() {
        return mDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_depth
     *
     * @param mDepth the value for menu.m_depth
     *
     * @mbggenerated
     */
    public void setmDepth(Integer mDepth) {
        this.mDepth = mDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_parent
     *
     * @return the value of menu.m_parent
     *
     * @mbggenerated
     */
    public String getmParent() {
        return mParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_parent
     *
     * @param mParent the value for menu.m_parent
     *
     * @mbggenerated
     */
    public void setmParent(String mParent) {
        this.mParent = mParent == null ? null : mParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_count
     *
     * @return the value of menu.m_count
     *
     * @mbggenerated
     */
    public Integer getmCount() {
        return mCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_count
     *
     * @param mCount the value for menu.m_count
     *
     * @mbggenerated
     */
    public void setmCount(Integer mCount) {
        this.mCount = mCount;
    }
}