package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PlatformMissData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_id
     *
     * @mbggenerated
     */
    private Integer pMDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_cwlsh
     *
     * @mbggenerated
     */
    private String pMDataCwlsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_ywlsh
     *
     * @mbggenerated
     */
    private String pMDataYwlsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_shddh
     *
     * @mbggenerated
     */
    private String pMDataShddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_spmc
     *
     * @mbggenerated
     */
    private String pMDataSpmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_time
     *
     * @mbggenerated
     */
    private Date pMDataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_dfzh
     *
     * @mbggenerated
     */
    private String pMDataDfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_srje
     *
     * @mbggenerated
     */
    private BigDecimal pMDataSrje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_zcje
     *
     * @mbggenerated
     */
    private BigDecimal pMDataZcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_ywlx
     *
     * @mbggenerated
     */
    private String pMDataYwlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.p_m_data_bz
     *
     * @mbggenerated
     */
    private String pMDataBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_miss_data.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_id
     *
     * @return the value of platform_miss_data.p_m_data_id
     *
     * @mbggenerated
     */
    public Integer getpMDataId() {
        return pMDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_id
     *
     * @param pMDataId the value for platform_miss_data.p_m_data_id
     *
     * @mbggenerated
     */
    public void setpMDataId(Integer pMDataId) {
        this.pMDataId = pMDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_cwlsh
     *
     * @return the value of platform_miss_data.p_m_data_cwlsh
     *
     * @mbggenerated
     */
    public String getpMDataCwlsh() {
        return pMDataCwlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_cwlsh
     *
     * @param pMDataCwlsh the value for platform_miss_data.p_m_data_cwlsh
     *
     * @mbggenerated
     */
    public void setpMDataCwlsh(String pMDataCwlsh) {
        this.pMDataCwlsh = pMDataCwlsh == null ? null : pMDataCwlsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_ywlsh
     *
     * @return the value of platform_miss_data.p_m_data_ywlsh
     *
     * @mbggenerated
     */
    public String getpMDataYwlsh() {
        return pMDataYwlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_ywlsh
     *
     * @param pMDataYwlsh the value for platform_miss_data.p_m_data_ywlsh
     *
     * @mbggenerated
     */
    public void setpMDataYwlsh(String pMDataYwlsh) {
        this.pMDataYwlsh = pMDataYwlsh == null ? null : pMDataYwlsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_shddh
     *
     * @return the value of platform_miss_data.p_m_data_shddh
     *
     * @mbggenerated
     */
    public String getpMDataShddh() {
        return pMDataShddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_shddh
     *
     * @param pMDataShddh the value for platform_miss_data.p_m_data_shddh
     *
     * @mbggenerated
     */
    public void setpMDataShddh(String pMDataShddh) {
        this.pMDataShddh = pMDataShddh == null ? null : pMDataShddh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_spmc
     *
     * @return the value of platform_miss_data.p_m_data_spmc
     *
     * @mbggenerated
     */
    public String getpMDataSpmc() {
        return pMDataSpmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_spmc
     *
     * @param pMDataSpmc the value for platform_miss_data.p_m_data_spmc
     *
     * @mbggenerated
     */
    public void setpMDataSpmc(String pMDataSpmc) {
        this.pMDataSpmc = pMDataSpmc == null ? null : pMDataSpmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_time
     *
     * @return the value of platform_miss_data.p_m_data_time
     *
     * @mbggenerated
     */
    public Date getpMDataTime() {
        return pMDataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_time
     *
     * @param pMDataTime the value for platform_miss_data.p_m_data_time
     *
     * @mbggenerated
     */
    public void setpMDataTime(Date pMDataTime) {
        this.pMDataTime = pMDataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_dfzh
     *
     * @return the value of platform_miss_data.p_m_data_dfzh
     *
     * @mbggenerated
     */
    public String getpMDataDfzh() {
        return pMDataDfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_dfzh
     *
     * @param pMDataDfzh the value for platform_miss_data.p_m_data_dfzh
     *
     * @mbggenerated
     */
    public void setpMDataDfzh(String pMDataDfzh) {
        this.pMDataDfzh = pMDataDfzh == null ? null : pMDataDfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_srje
     *
     * @return the value of platform_miss_data.p_m_data_srje
     *
     * @mbggenerated
     */
    public BigDecimal getpMDataSrje() {
        return pMDataSrje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_srje
     *
     * @param pMDataSrje the value for platform_miss_data.p_m_data_srje
     *
     * @mbggenerated
     */
    public void setpMDataSrje(BigDecimal pMDataSrje) {
        this.pMDataSrje = pMDataSrje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_zcje
     *
     * @return the value of platform_miss_data.p_m_data_zcje
     *
     * @mbggenerated
     */
    public BigDecimal getpMDataZcje() {
        return pMDataZcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_zcje
     *
     * @param pMDataZcje the value for platform_miss_data.p_m_data_zcje
     *
     * @mbggenerated
     */
    public void setpMDataZcje(BigDecimal pMDataZcje) {
        this.pMDataZcje = pMDataZcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_ywlx
     *
     * @return the value of platform_miss_data.p_m_data_ywlx
     *
     * @mbggenerated
     */
    public String getpMDataYwlx() {
        return pMDataYwlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_ywlx
     *
     * @param pMDataYwlx the value for platform_miss_data.p_m_data_ywlx
     *
     * @mbggenerated
     */
    public void setpMDataYwlx(String pMDataYwlx) {
        this.pMDataYwlx = pMDataYwlx == null ? null : pMDataYwlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.p_m_data_bz
     *
     * @return the value of platform_miss_data.p_m_data_bz
     *
     * @mbggenerated
     */
    public String getpMDataBz() {
        return pMDataBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.p_m_data_bz
     *
     * @param pMDataBz the value for platform_miss_data.p_m_data_bz
     *
     * @mbggenerated
     */
    public void setpMDataBz(String pMDataBz) {
        this.pMDataBz = pMDataBz == null ? null : pMDataBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.createtime
     *
     * @return the value of platform_miss_data.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.createtime
     *
     * @param createtime the value for platform_miss_data.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_miss_data.createuser
     *
     * @return the value of platform_miss_data.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_miss_data.createuser
     *
     * @param createuser the value for platform_miss_data.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}