package com.wwl.entity;

import java.util.Date;

public class Reconciliation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation.reconciliation_id
     *
     * @mbggenerated
     */
    private Integer reconciliationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation.reconciliation_date
     *
     * @mbggenerated
     */
    private Date reconciliationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation.reconciliation_result
     *
     * @mbggenerated
     */
    private Integer reconciliationResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation.reconciliation_desc
     *
     * @mbggenerated
     */
    private String reconciliationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation.reconciliation_id
     *
     * @return the value of reconciliation.reconciliation_id
     *
     * @mbggenerated
     */
    public Integer getReconciliationId() {
        return reconciliationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation.reconciliation_id
     *
     * @param reconciliationId the value for reconciliation.reconciliation_id
     *
     * @mbggenerated
     */
    public void setReconciliationId(Integer reconciliationId) {
        this.reconciliationId = reconciliationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation.reconciliation_date
     *
     * @return the value of reconciliation.reconciliation_date
     *
     * @mbggenerated
     */
    public Date getReconciliationDate() {
        return reconciliationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation.reconciliation_date
     *
     * @param reconciliationDate the value for reconciliation.reconciliation_date
     *
     * @mbggenerated
     */
    public void setReconciliationDate(Date reconciliationDate) {
        this.reconciliationDate = reconciliationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation.reconciliation_result
     *
     * @return the value of reconciliation.reconciliation_result
     *
     * @mbggenerated
     */
    public Integer getReconciliationResult() {
        return reconciliationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation.reconciliation_result
     *
     * @param reconciliationResult the value for reconciliation.reconciliation_result
     *
     * @mbggenerated
     */
    public void setReconciliationResult(Integer reconciliationResult) {
        this.reconciliationResult = reconciliationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation.reconciliation_desc
     *
     * @return the value of reconciliation.reconciliation_desc
     *
     * @mbggenerated
     */
    public String getReconciliationDesc() {
        return reconciliationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation.reconciliation_desc
     *
     * @param reconciliationDesc the value for reconciliation.reconciliation_desc
     *
     * @mbggenerated
     */
    public void setReconciliationDesc(String reconciliationDesc) {
        this.reconciliationDesc = reconciliationDesc == null ? null : reconciliationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation.createtime
     *
     * @return the value of reconciliation.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation.createtime
     *
     * @param createtime the value for reconciliation.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation.createuser
     *
     * @return the value of reconciliation.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation.createuser
     *
     * @param createuser the value for reconciliation.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}