package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ReconciliationDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_id
     *
     * @mbggenerated
     */
    private Integer rDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_code
     *
     * @mbggenerated
     */
    private String rDetailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_srccode
     *
     * @mbggenerated
     */
    private String rDetailSrccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_reconciliation_id
     *
     * @mbggenerated
     */
    private Integer rReconciliationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_type
     *
     * @mbggenerated
     */
    private String rDetailType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_date
     *
     * @mbggenerated
     */
    private Date rDetailDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_qssjf
     *
     * @mbggenerated
     */
    private String rDetailQssjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_je
     *
     * @mbggenerated
     */
    private BigDecimal rDetailJe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_sxf
     *
     * @mbggenerated
     */
    private BigDecimal rDetailSxf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_ptbk
     *
     * @mbggenerated
     */
    private BigDecimal rDetailPtbk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_result
     *
     * @mbggenerated
     */
    private Integer rDetailResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_reason
     *
     * @mbggenerated
     */
    private Integer rDetailReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.r_detail_bz
     *
     * @mbggenerated
     */
    private String rDetailBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.cztime
     *
     * @mbggenerated
     */
    private Date cztime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reconciliation_detail.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_id
     *
     * @return the value of reconciliation_detail.r_detail_id
     *
     * @mbggenerated
     */
    public Integer getrDetailId() {
        return rDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_id
     *
     * @param rDetailId the value for reconciliation_detail.r_detail_id
     *
     * @mbggenerated
     */
    public void setrDetailId(Integer rDetailId) {
        this.rDetailId = rDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_code
     *
     * @return the value of reconciliation_detail.r_detail_code
     *
     * @mbggenerated
     */
    public String getrDetailCode() {
        return rDetailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_code
     *
     * @param rDetailCode the value for reconciliation_detail.r_detail_code
     *
     * @mbggenerated
     */
    public void setrDetailCode(String rDetailCode) {
        this.rDetailCode = rDetailCode == null ? null : rDetailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_srccode
     *
     * @return the value of reconciliation_detail.r_detail_srccode
     *
     * @mbggenerated
     */
    public String getrDetailSrccode() {
        return rDetailSrccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_srccode
     *
     * @param rDetailSrccode the value for reconciliation_detail.r_detail_srccode
     *
     * @mbggenerated
     */
    public void setrDetailSrccode(String rDetailSrccode) {
        this.rDetailSrccode = rDetailSrccode == null ? null : rDetailSrccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_reconciliation_id
     *
     * @return the value of reconciliation_detail.r_reconciliation_id
     *
     * @mbggenerated
     */
    public Integer getrReconciliationId() {
        return rReconciliationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_reconciliation_id
     *
     * @param rReconciliationId the value for reconciliation_detail.r_reconciliation_id
     *
     * @mbggenerated
     */
    public void setrReconciliationId(Integer rReconciliationId) {
        this.rReconciliationId = rReconciliationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_type
     *
     * @return the value of reconciliation_detail.r_detail_type
     *
     * @mbggenerated
     */
    public String getrDetailType() {
        return rDetailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_type
     *
     * @param rDetailType the value for reconciliation_detail.r_detail_type
     *
     * @mbggenerated
     */
    public void setrDetailType(String rDetailType) {
        this.rDetailType = rDetailType == null ? null : rDetailType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_date
     *
     * @return the value of reconciliation_detail.r_detail_date
     *
     * @mbggenerated
     */
    public Date getrDetailDate() {
        return rDetailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_date
     *
     * @param rDetailDate the value for reconciliation_detail.r_detail_date
     *
     * @mbggenerated
     */
    public void setrDetailDate(Date rDetailDate) {
        this.rDetailDate = rDetailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_qssjf
     *
     * @return the value of reconciliation_detail.r_detail_qssjf
     *
     * @mbggenerated
     */
    public String getrDetailQssjf() {
        return rDetailQssjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_qssjf
     *
     * @param rDetailQssjf the value for reconciliation_detail.r_detail_qssjf
     *
     * @mbggenerated
     */
    public void setrDetailQssjf(String rDetailQssjf) {
        this.rDetailQssjf = rDetailQssjf == null ? null : rDetailQssjf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_je
     *
     * @return the value of reconciliation_detail.r_detail_je
     *
     * @mbggenerated
     */
    public BigDecimal getrDetailJe() {
        return rDetailJe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_je
     *
     * @param rDetailJe the value for reconciliation_detail.r_detail_je
     *
     * @mbggenerated
     */
    public void setrDetailJe(BigDecimal rDetailJe) {
        this.rDetailJe = rDetailJe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_sxf
     *
     * @return the value of reconciliation_detail.r_detail_sxf
     *
     * @mbggenerated
     */
    public BigDecimal getrDetailSxf() {
        return rDetailSxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_sxf
     *
     * @param rDetailSxf the value for reconciliation_detail.r_detail_sxf
     *
     * @mbggenerated
     */
    public void setrDetailSxf(BigDecimal rDetailSxf) {
        this.rDetailSxf = rDetailSxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_ptbk
     *
     * @return the value of reconciliation_detail.r_detail_ptbk
     *
     * @mbggenerated
     */
    public BigDecimal getrDetailPtbk() {
        return rDetailPtbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_ptbk
     *
     * @param rDetailPtbk the value for reconciliation_detail.r_detail_ptbk
     *
     * @mbggenerated
     */
    public void setrDetailPtbk(BigDecimal rDetailPtbk) {
        this.rDetailPtbk = rDetailPtbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_result
     *
     * @return the value of reconciliation_detail.r_detail_result
     *
     * @mbggenerated
     */
    public Integer getrDetailResult() {
        return rDetailResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_result
     *
     * @param rDetailResult the value for reconciliation_detail.r_detail_result
     *
     * @mbggenerated
     */
    public void setrDetailResult(Integer rDetailResult) {
        this.rDetailResult = rDetailResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_reason
     *
     * @return the value of reconciliation_detail.r_detail_reason
     *
     * @mbggenerated
     */
    public Integer getrDetailReason() {
        return rDetailReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_reason
     *
     * @param rDetailReason the value for reconciliation_detail.r_detail_reason
     *
     * @mbggenerated
     */
    public void setrDetailReason(Integer rDetailReason) {
        this.rDetailReason = rDetailReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.r_detail_bz
     *
     * @return the value of reconciliation_detail.r_detail_bz
     *
     * @mbggenerated
     */
    public String getrDetailBz() {
        return rDetailBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.r_detail_bz
     *
     * @param rDetailBz the value for reconciliation_detail.r_detail_bz
     *
     * @mbggenerated
     */
    public void setrDetailBz(String rDetailBz) {
        this.rDetailBz = rDetailBz == null ? null : rDetailBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.cztime
     *
     * @return the value of reconciliation_detail.cztime
     *
     * @mbggenerated
     */
    public Date getCztime() {
        return cztime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.cztime
     *
     * @param cztime the value for reconciliation_detail.cztime
     *
     * @mbggenerated
     */
    public void setCztime(Date cztime) {
        this.cztime = cztime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.createtime
     *
     * @return the value of reconciliation_detail.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.createtime
     *
     * @param createtime the value for reconciliation_detail.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reconciliation_detail.createuser
     *
     * @return the value of reconciliation_detail.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reconciliation_detail.createuser
     *
     * @param createuser the value for reconciliation_detail.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}