package com.wwl.entity;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.r_menu_id
     *
     * @mbggenerated
     */
    private Integer rMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.r_menu_role_id
     *
     * @mbggenerated
     */
    private Integer rMenuRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.r_menu_code
     *
     * @mbggenerated
     */
    private String rMenuCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.r_menu_id
     *
     * @return the value of role_menu.r_menu_id
     *
     * @mbggenerated
     */
    public Integer getrMenuId() {
        return rMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.r_menu_id
     *
     * @param rMenuId the value for role_menu.r_menu_id
     *
     * @mbggenerated
     */
    public void setrMenuId(Integer rMenuId) {
        this.rMenuId = rMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.r_menu_role_id
     *
     * @return the value of role_menu.r_menu_role_id
     *
     * @mbggenerated
     */
    public Integer getrMenuRoleId() {
        return rMenuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.r_menu_role_id
     *
     * @param rMenuRoleId the value for role_menu.r_menu_role_id
     *
     * @mbggenerated
     */
    public void setrMenuRoleId(Integer rMenuRoleId) {
        this.rMenuRoleId = rMenuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.r_menu_code
     *
     * @return the value of role_menu.r_menu_code
     *
     * @mbggenerated
     */
    public String getrMenuCode() {
        return rMenuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.r_menu_code
     *
     * @param rMenuCode the value for role_menu.r_menu_code
     *
     * @mbggenerated
     */
    public void setrMenuCode(String rMenuCode) {
        this.rMenuCode = rMenuCode == null ? null : rMenuCode.trim();
    }
}