package com.wwl.entity;

import java.util.Date;

public class SettlementType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_type.s_type_id
     *
     * @mbggenerated
     */
    private Integer sTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_type.s_type_name
     *
     * @mbggenerated
     */
    private String sTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_type.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_type.createuser
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_type.s_type_id
     *
     * @return the value of settlement_type.s_type_id
     *
     * @mbggenerated
     */
    public Integer getsTypeId() {
        return sTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_type.s_type_id
     *
     * @param sTypeId the value for settlement_type.s_type_id
     *
     * @mbggenerated
     */
    public void setsTypeId(Integer sTypeId) {
        this.sTypeId = sTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_type.s_type_name
     *
     * @return the value of settlement_type.s_type_name
     *
     * @mbggenerated
     */
    public String getsTypeName() {
        return sTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_type.s_type_name
     *
     * @param sTypeName the value for settlement_type.s_type_name
     *
     * @mbggenerated
     */
    public void setsTypeName(String sTypeName) {
        this.sTypeName = sTypeName == null ? null : sTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_type.createtime
     *
     * @return the value of settlement_type.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_type.createtime
     *
     * @param createtime the value for settlement_type.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_type.createuser
     *
     * @return the value of settlement_type.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_type.createuser
     *
     * @param createuser the value for settlement_type.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }
}