package com.wwl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TenpayMissData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_id
     *
     * @mbggenerated
     */
    private Integer tMDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_ddh
     *
     * @mbggenerated
     */
    private String tMDataDdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_shddh
     *
     * @mbggenerated
     */
    private String tMDataShddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_name
     *
     * @mbggenerated
     */
    private String tMDataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_jysj
     *
     * @mbggenerated
     */
    private Date tMDataJysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_jyf
     *
     * @mbggenerated
     */
    private String tMDataJyf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_srje
     *
     * @mbggenerated
     */
    private BigDecimal tMDataSrje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_zcje
     *
     * @mbggenerated
     */
    private BigDecimal tMDataZcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_jylx
     *
     * @mbggenerated
     */
    private String tMDataJylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.t_m_data_jyxx
     *
     * @mbggenerated
     */
    private String tMDataJyxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenpay_miss_data.createuser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_id
     *
     * @return the value of tenpay_miss_data.t_m_data_id
     *
     * @mbggenerated
     */
    public Integer gettMDataId() {
        return tMDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_id
     *
     * @param tMDataId the value for tenpay_miss_data.t_m_data_id
     *
     * @mbggenerated
     */
    public void settMDataId(Integer tMDataId) {
        this.tMDataId = tMDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_ddh
     *
     * @return the value of tenpay_miss_data.t_m_data_ddh
     *
     * @mbggenerated
     */
    public String gettMDataDdh() {
        return tMDataDdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_ddh
     *
     * @param tMDataDdh the value for tenpay_miss_data.t_m_data_ddh
     *
     * @mbggenerated
     */
    public void settMDataDdh(String tMDataDdh) {
        this.tMDataDdh = tMDataDdh == null ? null : tMDataDdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_shddh
     *
     * @return the value of tenpay_miss_data.t_m_data_shddh
     *
     * @mbggenerated
     */
    public String gettMDataShddh() {
        return tMDataShddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_shddh
     *
     * @param tMDataShddh the value for tenpay_miss_data.t_m_data_shddh
     *
     * @mbggenerated
     */
    public void settMDataShddh(String tMDataShddh) {
        this.tMDataShddh = tMDataShddh == null ? null : tMDataShddh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_name
     *
     * @return the value of tenpay_miss_data.t_m_data_name
     *
     * @mbggenerated
     */
    public String gettMDataName() {
        return tMDataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_name
     *
     * @param tMDataName the value for tenpay_miss_data.t_m_data_name
     *
     * @mbggenerated
     */
    public void settMDataName(String tMDataName) {
        this.tMDataName = tMDataName == null ? null : tMDataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_jysj
     *
     * @return the value of tenpay_miss_data.t_m_data_jysj
     *
     * @mbggenerated
     */
    public Date gettMDataJysj() {
        return tMDataJysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_jysj
     *
     * @param tMDataJysj the value for tenpay_miss_data.t_m_data_jysj
     *
     * @mbggenerated
     */
    public void settMDataJysj(Date tMDataJysj) {
        this.tMDataJysj = tMDataJysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_jyf
     *
     * @return the value of tenpay_miss_data.t_m_data_jyf
     *
     * @mbggenerated
     */
    public String gettMDataJyf() {
        return tMDataJyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_jyf
     *
     * @param tMDataJyf the value for tenpay_miss_data.t_m_data_jyf
     *
     * @mbggenerated
     */
    public void settMDataJyf(String tMDataJyf) {
        this.tMDataJyf = tMDataJyf == null ? null : tMDataJyf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_srje
     *
     * @return the value of tenpay_miss_data.t_m_data_srje
     *
     * @mbggenerated
     */
    public BigDecimal gettMDataSrje() {
        return tMDataSrje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_srje
     *
     * @param tMDataSrje the value for tenpay_miss_data.t_m_data_srje
     *
     * @mbggenerated
     */
    public void settMDataSrje(BigDecimal tMDataSrje) {
        this.tMDataSrje = tMDataSrje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_zcje
     *
     * @return the value of tenpay_miss_data.t_m_data_zcje
     *
     * @mbggenerated
     */
    public BigDecimal gettMDataZcje() {
        return tMDataZcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_zcje
     *
     * @param tMDataZcje the value for tenpay_miss_data.t_m_data_zcje
     *
     * @mbggenerated
     */
    public void settMDataZcje(BigDecimal tMDataZcje) {
        this.tMDataZcje = tMDataZcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_jylx
     *
     * @return the value of tenpay_miss_data.t_m_data_jylx
     *
     * @mbggenerated
     */
    public String gettMDataJylx() {
        return tMDataJylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_jylx
     *
     * @param tMDataJylx the value for tenpay_miss_data.t_m_data_jylx
     *
     * @mbggenerated
     */
    public void settMDataJylx(String tMDataJylx) {
        this.tMDataJylx = tMDataJylx == null ? null : tMDataJylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.t_m_data_jyxx
     *
     * @return the value of tenpay_miss_data.t_m_data_jyxx
     *
     * @mbggenerated
     */
    public String gettMDataJyxx() {
        return tMDataJyxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.t_m_data_jyxx
     *
     * @param tMDataJyxx the value for tenpay_miss_data.t_m_data_jyxx
     *
     * @mbggenerated
     */
    public void settMDataJyxx(String tMDataJyxx) {
        this.tMDataJyxx = tMDataJyxx == null ? null : tMDataJyxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.createtime
     *
     * @return the value of tenpay_miss_data.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.createtime
     *
     * @param createtime the value for tenpay_miss_data.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenpay_miss_data.createuser
     *
     * @return the value of tenpay_miss_data.createuser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenpay_miss_data.createuser
     *
     * @param createuser the value for tenpay_miss_data.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }
}