package com.wwl.entity;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_username
     *
     * @mbggenerated
     */
    private String uUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_relname
     *
     * @mbggenerated
     */
    private String uRelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_password
     *
     * @mbggenerated
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_role_id
     *
     * @mbggenerated
     */
    private Integer uRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_status
     *
     * @mbggenerated
     */
    private Integer uStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_createtime
     *
     * @mbggenerated
     */
    private Date uCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_id
     *
     * @return the value of users.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_id
     *
     * @param uId the value for users.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_username
     *
     * @return the value of users.u_username
     *
     * @mbggenerated
     */
    public String getuUsername() {
        return uUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_username
     *
     * @param uUsername the value for users.u_username
     *
     * @mbggenerated
     */
    public void setuUsername(String uUsername) {
        this.uUsername = uUsername == null ? null : uUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_relname
     *
     * @return the value of users.u_relname
     *
     * @mbggenerated
     */
    public String getuRelname() {
        return uRelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_relname
     *
     * @param uRelname the value for users.u_relname
     *
     * @mbggenerated
     */
    public void setuRelname(String uRelname) {
        this.uRelname = uRelname == null ? null : uRelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_password
     *
     * @return the value of users.u_password
     *
     * @mbggenerated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_password
     *
     * @param uPassword the value for users.u_password
     *
     * @mbggenerated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_role_id
     *
     * @return the value of users.u_role_id
     *
     * @mbggenerated
     */
    public Integer getuRoleId() {
        return uRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_role_id
     *
     * @param uRoleId the value for users.u_role_id
     *
     * @mbggenerated
     */
    public void setuRoleId(Integer uRoleId) {
        this.uRoleId = uRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_status
     *
     * @return the value of users.u_status
     *
     * @mbggenerated
     */
    public Integer getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_status
     *
     * @param uStatus the value for users.u_status
     *
     * @mbggenerated
     */
    public void setuStatus(Integer uStatus) {
        this.uStatus = uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_createtime
     *
     * @return the value of users.u_createtime
     *
     * @mbggenerated
     */
    public Date getuCreatetime() {
        return uCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_createtime
     *
     * @param uCreatetime the value for users.u_createtime
     *
     * @mbggenerated
     */
    public void setuCreatetime(Date uCreatetime) {
        this.uCreatetime = uCreatetime;
    }
}